### ISSUE TITLE
No inputs were found in config file

### ISSUE THREAD

**Issue by s4m0r4m4** [nrwl/nx-console#1014]
Sometimes when I try to generate a component via a **custom workspace schematic** using nx console, it throws the following error:

`error TS18003: No inputs were found in config file 'C:/Development/.../tools/tsconfig.generated.json'. Specified 'include' paths were '["C:\\Development\\...\\tools\\generators\\**\\*.ts"]' and 'exclude' paths were '["../node_modules","../tmp"]'.`

Which makes sense, because I don't have any files under tools\generators. All my schematics are under tools/schematics. Am I supposed to be storing the schematics under the generators folder instead? When I move my schematics to the generators folder, I get the following error:

```
C:\Development\...\node_modules\typescript\lib\tsc.js:84799
                throw e;
                ^

Error: Debug Failure. False expression: Too many nodes written to output.
    at extractSingleNode (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:65899:18)
    at Object.visitNode (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:65472:54) 
    at transformCommonJSModule (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:75043:38)
    at transformSourceFile (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:75020:27)
    at transformSourceFileOrBundle (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:66514:40)
    at transformation (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:78598:24)
    at transformRoot (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:78616:82)
    at Object.map (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:373:29)
    at Object.transformNodes (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:78603:30)
    at emitJsFileOrBundle (C:\Development\greenatlas\node_modules\typescript\lib\tsc.js:79130:32)
```

Note: I run into these same errors if I try to run the schematic from the command line.

**Comment by Cammisuli** [comment]
This looks like you updated your Nx workspace deps but didn't run a migration. There should've been one when updating to 11.2.

You can see how it was changed for me when trying to update the deps for this repo here: https://github.com/nrwl/nx-console/pull/1013/commits/a57d19a636ff7459817cc4899ec89ad88c200836

**Comment by Cammisuli** [comment]
If you're still having issues with this, please open an issue on the [Nrwl/nx](https://github.com/nrwl/nx/issues/new/choose) repo

**Comment by s4m0r4m4** [comment]
Yeah you're right, I did move these schematics over from a v10 repo to a different repo that was already on v11, so it missed the migration.
