### ISSUE TITLE
nx console vs code fails to execute commands

### ISSUE THREAD

**Issue by jonastg** [nrwl/nx-console#1093]
When I execute a command, like nx serve, it fails due to node versión. My default node versión is v8 and for this project I use v12, the node version changes automatically when I access to folders and they contains and `.nvmrc` with the desire version. Configuration [here](https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file-1).

```bash
> Executing task in folder PULPO-WEB-FRONT: ng serve operations -c=development --progress --verbose <

<path...>/node_modules/yargs-parser/build/index.cjs:983
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (<path...>/node_modules/yargs-parser/build/index.cjs:983:15)
    at Module._compile (<path...>/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (<path...>/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (<path...>/node_modules/@nrwl/cli/lib/parse-run-one-options.js:4:21)
    at Module._compile (<path...>/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
The terminal process "/bin/bash '-l', '-c', '<path...>/node_modules/.bin/ng serve operations -c=development --progress --verbose', 'ng serve operations -c=development --progress --verbose'" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```

If I open a new terminal through vs code it initializes correctly and I can launch commands manually.

```bash
Now using node v12.22.1 (npm v6.14.12)
user@machine:~/<path...>$ 
```
So, the problem seems to be that the console initialization it's different to a normal bash terminal and it doesn't takes into account `.bashrc` configuration.

System info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

VS Code:
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```
NX Console `v17.5.1`

**Comment by Cammisuli** [comment]
I know with nvmrc we have to specifically execute the command `nvm use`. 

Do you have this in your bash profile?

https://github.com/nvm-sh/nvm#automatically-call-nvm-use

That will make bash find the closest nvmrc and execute `nvm use`. 

We apparently have a `useNVM` option that doesn't do anything ☹️ 

Also, I really, really suggest you upgrade your global node. V8 is very old and probably has some security issues that are not resolved.

**Comment by Cammisuli** [comment]
The code to get the bash executable is here:

https://github.com/nrwl/nx-console/blob/98d4d7118a19b07345146fdd01c56c7e55e896a6/libs/vscode/tasks/src/lib/shell-execution.ts#L42

I can take a deeper look later next week.

**Comment by jonastg** [comment]
Thank you, @Cammisuli for your quick response. Yess! I have that configuration and I can't change the default node version because it's required by other projects. It is like if shell initialization doesn't load .bashrc file so it uses the default v8.

**Comment by genu** [comment]
Possible to remove the bash dependency all-together? Is there a reason we're tied to it -- what's the rationale here?

I use neither bash nor zsh, I use fish shell, so every command in nx console fails with:

```bash
> Executing task: nx list <

env: node: No such file or directory
The terminal process "/bin/bash '-l', '-c', '/Users/owner/git/temp_project/node_modules/.bin/nx list', 'nx list'" terminated with exit code: 127.

Terminal will be reused by tasks, press any key to close it.`

**Comment by genu** [comment]
I don't think this part should be hardcoded. Is there a way to get the default shell instead? (In OSX, for example, the default shell can be configured)

-- OR --

Add a configuration option to set the `bashPath`

https://github.com/nrwl/nx-console/blob/2f58b0028c8e0b1bb685618fd1a61644da4cffc9/libs/vscode/tasks/src/lib/shell-execution.ts#L45

**Comment by Cammisuli** [comment]
Yea, I don't see why not. It's something that I have to investigate still.

**Comment by acmoune** [comment]
I added this at the end of  `~/.profile`, and everything works fine, I think **Nx Console** initialize itself with `.profile`, and doesn't consider **.bashrc**

```
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
