### ISSUE TITLE
can't target any project with nx-17.11.0 

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx-console#1144]
![image](https://user-images.githubusercontent.com/456807/134768287-2f6fafd3-54f3-4096-acaa-9e51c55590d5.png)

usually it will pull all projects when you click run, build etc. 

After updating to 17.11.0, it doesn't work anymore. I have to rollback to 17.10.0 to make it work again.

I use `workspace.json` with `project.json`

**Comment by chrismcleod** [comment]
i get same error and roll back helps.  This is the only error i see:

![image](https://user-images.githubusercontent.com/1134683/134789885-b37809e6-0e82-400c-b7e4-24aad29f6d79.png)

**Comment by Cammisuli** [comment]
Sorry about that everyone! I'm looking into this now..

**Comment by Cammisuli** [comment]
Fix should be in 17.11.1

**Comment by maxisam** [comment]
@Cammisuli it still doesn't work.

**Comment by Cammisuli** [comment]
@maxisam does the issue still happen if you open the https://github.com/nrwl/nx repo? That's also using workspace.json and project.json files

**Comment by Cammisuli** [comment]
Also what environment is being used?

**Comment by labeled** [comment]
@Cammisuli yes I pulled down latest nx-example repo, upgraded the extension to the latest and I see the same error.

**Comment by Cammisuli** [comment]
@labeled  Windows, Linux, web, macOS?

**Comment by labeled** [comment]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎4/‎21/‎2021
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by Cammisuli** [comment]
17.11.2 should fix Windows now

**Comment by labeled** [comment]
@Cammisuli I have verified the issue no longer exists. Thanks for the quick fix!

**Comment by maxisam** [comment]
@Cammisuli  it works now

**Comment by mackelito** [comment]
Hmm.. I just got this issue as well.. but I have the latest versions of both VS Code and NX console..?

**Comment by ar-to** [comment]
started seen this all of the sudden too. The only thing I did different lately is install [liveshare](https://code.visualstudio.com/learn/collaboration/live-share) and then tried everything I could think of to get nx console to work again.

**Comment by Cammisuli** [comment]
#1197 is the latest issue that's tracking some problems with the 17.13 release of console. Read through that. I also published a newer version of nx console that I'm hoping will solve the last bits of this issue.

**Comment by mauricioross** [comment]
In my case, today, when make a workspace and add angular nrwl, the version of this are ^999.9.9, and then i go to https://nx.dev/angular-nx-version-matrix and change version for the latest version of nrwl angular, and this solve for me

**Comment by FrancescoBorzi** [comment]
I'm getting the same problem on `15.9.2` using macOS

**Comment by nicky-lenaers** [comment]
I am getting the same error when running `npx nx g @nrwl/angular:scam-to-standalone`

**Comment by skwny** [comment]
> I'm getting the same problem on `15.9.2` using macOS when trying to run
> 
> ```
>  nx g @nrwl/workspace:fix-configuration  
> ```

Getting error on same command as well.

**Comment by rebeccadavidsson** [comment]
Same error while running **any** nx command after updating to nx-15.9.2

**Comment by paviln** [comment]
Using @nrwl/vite": "^15.9.2", and running dev-server with env development, gives the following error: Running target dev-server for project staff-web failed

**Comment by renericardoperez** [comment]
Same error when running 

```bash
nx generate @nxtend/firebase:firebase-project --project {project-name}
```

![Screenshot 2023-06-11 at 12 26 12](https://github.com/nrwl/nx-console/assets/32307287/d5e58e74-7553-416c-abc7-797ddf0a1b0c)

**Comment by guzmanxp** [comment]
Same error NX Console V 18.5.0
<img width="941" alt="image" src="https://github.com/nrwl/nx-console/assets/19859215/2af3012b-ef67-4b34-95ce-266ecb278c93">

**Comment by deving1995** [comment]
Same error when running `nx generate scam-to-standalone`

**Comment by ElesGergo** [comment]
![image](https://github.com/nrwl/nx-console/assets/31933098/f2d79917-a32b-4488-ae60-cb5c14cb2802)
My Nx project is not even recognized anymore I am getting the same error on "Refresh Workspace"

**Comment by zachdixon** [comment]
I just encountered this error and it was because we moved the `app` folder (nested it in another folder). Moving it back to `shell-app-name/src/app` made the generator work again. The code in `update-host-with-remote.js` looks for the app component in that specific location:

```
function findAppComponentPath(host, sourceRoot) {
    const locations = ['app/app.tsx', 'app/App.tsx', 'app.tsx', 'App.tsx'];
    for (const loc of locations) {
        if (host.exists((0, devkit_1.joinPathFragments)(sourceRoot, loc))) {
            return (0, devkit_1.joinPathFragments)(sourceRoot, loc);
        }
    }
}

**Comment by skwny** [comment]
Happened when running `nx generate @nxtend/firebase:firebase-project --project 'backend' --verbose`.

Output:
```
  NX  Generating @nxtend/firebase:firebase-project


 >  NX   The "path" argument must be of type string. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:1171:7)
    at FsTree.normalize (/Users/user/git/project/node_modules/nx/src/generators/tree.js:225:64)
    at FsTree.exists (/Users/user/git/project/node_modules/nx/src/generators/tree.js:94:25)
    at Object.readJson (/Users/user/git/project/node_modules/@nxtend/firebase/node_modules/@nrwl/devkit/src/utils/json.js:13:15)
    at inlineProjectConfigurationsWithTree (/Users/user/git/project/node_modules/@nxtend/firebase/node_modules/@nrwl/devkit/src/generators/project-configuration.js:280:34)
    at readWorkspace (/Users/user/git/project/node_modules/@nxtend/firebase/node_modules/@nrwl/devkit/src/generators/project-configuration.js:268:27)
    at Object.readProjectConfiguration (/Users/user/git/project/node_modules/@nxtend/firebase/node_modules/@nrwl/devkit/src/generators/project-configuration.js:158:23)
    at Object.addProject (/Users/user/git/project/node_modules/@nxtend/firebase/src/generators/firebase-project/lib/add-project.js:6:43)
user@user project % nx generate @nxtend/firebase:firebase-project --project 'backend' --verbose
```

**Comment by Krasnov8953** [comment]
getting same error with npx nx@latest init in macOS Ventura 13.3 (22E252)

`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:1172:7)
    at projectHasEslintConfig (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/implementation/angular/standalone-workspace.js:164:57)
    at getWorkspaceCapabilities (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/implementation/angular/standalone-workspace.js:139:13)
    at setupStandaloneWorkspace (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/implementation/angular/standalone-workspace.js:13:35)
    at setupWorkspace (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/implementation/angular/index.js:113:67)
    at addNxToAngularCliRepo (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/implementation/angular/index.js:42:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initHandler (/Users/krasnovvalerij/fsx/www/frontend/node_modules/nx/src/command-line/init/init.js:30:13) {
  code: 'ERR_INVALID_ARG_TYPE'
`

**Comment by Firfi** [comment]
got this error just randomly `The "path" argument must be of type string. Received undefined` - no changes to the project at all! running `npx nx run-many --target=build --all`

**Comment by MaxKless** [comment]
hey everyone thanks for the reports. It looks like none of the recent comments have anything to do with the above issue, but instead specific plugin generators.
If you find an issue, make sure to submit an issue in the corresponding repo. 
I'll lock this for now.
