### ISSUE TITLE
Client is not running

### ISSUE THREAD

**Issue by MartinPELCAT** [nrwl/nx-console#1440]
## Current Behavior

Nx extension is not working with the latest version on VsCode.
![image](https://user-images.githubusercontent.com/35460122/207269922-d1d86422-2c1f-4be7-b275-298cc91b197c.png)

![image](https://user-images.githubusercontent.com/35460122/207270344-1737d7d5-78b8-45be-b727-a84ecc50d5e7.png)

## Expected Behavior

Works fine with the previous version (17.26.0) but not the latest.
![image](https://user-images.githubusercontent.com/35460122/207270701-a9993108-33da-4ee4-8a1f-a47d0515111b.png)

### Failure Logs / Images / Videos

"Output" of nx console client in vscode 

```
/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher

    at Function.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/nxls/main.js:213:9822)
[Info  - 4:01:00 PM] Connection to server got closed. Server will restart.
[Error - 4:01:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher

    at Function.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/nxls/main.js:213:9822)
[Info  - 4:01:00 PM] Connection to server got closed. Server will restart.
[Error - 4:01:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher

    at Function.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/nxls/main.js:213:9822)
[Info  - 4:01:00 PM] Connection to server got closed. Server will restart.
[Error - 4:01:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher

    at Function.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/nxls/main.js:213:9822)
[Info  - 4:01:00 PM] Connection to server got closed. Server will restart.
[Error - 4:01:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher

    at Function.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.27.0/nxls/main.js:213:9822)
[Error - 4:01:00 PM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:01:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:01:00 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

### Environment

* MacOs : 12.6
* CPU architecture : ARM/x64 M2
* docker desktop : \[4.12.0\]
* vscode : 1.74.0
* vscode devcontainer extension : v0.266.1

**Comment by MaxKless** [comment]
Have you tried on version `17.27.1` ?

**Comment by MartinPELCAT** [comment]
@MaxKless Yes same problem

**Comment by Cammisuli** [comment]
Hmm.. It looks like we're missing a linux build for the parcel/watcher.

**Comment by ijaouani** [comment]
I reproduce the same issue on Apple M1 with a minimal nx workspace while it's working on Windows x64. Seems like a platform specific issue : https://github.com/parcel-bundler/watcher/issues/101

**Comment by craigbroadman** [comment]
I have the same error on my Windows 10 machine

**Comment by Cammisuli** [comment]
@ijaouani  I just tried this out on a M1 Macbook Air, and Nx Console looks to be working there.. Looks like a deeper investigation is needed 🤔 

@craigbroadman I'll give it a try on a Windows 10 machine as well (if I can find one 😮)

**Comment by foxriver76** [comment]
Same issue building our monorepo with lerna and nx on Mac M1 (local running Ubuntu VM)

```
npm run build

> prebuild
> rimraf packages/*/build packages/*/*.tsbuildinfo


> build
> npm run build:ts


> build:ts
> lerna run build

lerna notice cli v6.1.0

 >  Lerna (powered by Nx)   No native build was found for platform=linux arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.12.1

       loaded from: /home/moritz/workspaces/ioBroker.js-controller/node_modules/@parcel/watcher
   
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

**Comment by MaxKless** [comment]
This works with the latest versions of nx & `@angular-architects/ddd`. The `no-app` flag got renamed to `noApp`.

**Comment by ijaouani** [comment]
@Cammisuli I have created a minimal repo to reproduce the issue : https://github.com/ijaouani/nx-console-1440

How to :

1. Clone this repo locally
2. Open it inside a devcontainer (a pop up should automatically appears if you already have Docker Desktop and Remote Extension installed).
3. On the Nx Console extension try to open the nx project 

Results :

1. On a local Windows everything is working as expected
2. On a local Mac M* (ARM) :

```
/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.1/nxls/main.js:213:9822)
[Info  - 2:37:11 PM] Connection to server got closed. Server will restart.
[Error - 2:37:11 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by DromaderBosse** [comment]
Exactly the same symptoms as @MartinPELCAT

- Mac M1
- OS: Ubuntu 22.04.1 LTS (Linux arm64 5.15.0-58-generic) (VM)
- Node.js: 16.14.2
- nx: 15.3.3
- VSCode: 1.74.3

**Comment by mstephenson6** [comment]
I am seeing the same error running Arch/Asahi on M1. I discovered I can force @parcel/watcher to build itself for Linux aarch64 with these steps, from my nx project root:

```
$ cd node_modules/@parcel/watcher/
$ npm install
$ npm run prebuild
```

This creates a new directory `prebuilds/linux-arm64`

After this, things that depend on @parcel/watcher work, like `nx serve`

**Comment by AdamSundberg** [comment]
I have the exact same problem as @ijaouani when working with devcontainers. On a windows machine with docker desktop and WSL it works. But on a Macbook M2 I get the same error.

```cmd
/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Info  - 9:27:04 PM] Connection to server got closed. Server will restart.
[Error - 9:27:04 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

The extension works perfectly on my mac locally (when I don't use devcontainers). See below for my devcontainer.json and Dockerfile.

devcontainer.json
```json
{
  "name": "App",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "remoteUser": "node",
  "postCreateCommand": "npm install",
  "customizations": {
    "vscode": {
      "extensions": [
        "nrwl.angular-console",
        "esbenp.prettier-vscode",
        "firsttris.vscode-jest-runner",
        "dbaeumer.vscode-eslint",
        "Angular.ng-template",
        "unifiedjs.vscode-mdx",
        "aaron-bond.better-comments",
        "eamodio.gitlens"
      ]
    }
  }
}
```
Dockerfile
```Dockerfile
FROM node:18

# Install basic development tools
RUN apt update && apt install -y less man-db sudo

# Ensure default `node` user has access to `sudo`
ARG USERNAME=node
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true
``` 

I've tried what @mstephenson6 suggested but then I get this error.
```cmd
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.10.104-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=10.0.0" "--devdir=/tmp/prebuildify/node" "--arch=arm64" "--build_v8_with_gn=false" "--release"
gyp ERR! cwd /home/node/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher
gyp ERR! node -v v18.13.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
node-gyp exited with 1
```

**Comment by jerico-wf** [comment]
Facing the same problem on devcontainer 

```bash
/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Info  - 9:07:22 AM] Connection to server got closed. Server will restart.
[Error - 9:07:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Info  - 9:07:22 AM] Connection to server got closed. Server will restart.
[Error - 9:07:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Info  - 9:07:22 AM] Connection to server got closed. Server will restart.
[Error - 9:07:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Info  - 9:07:22 AM] Connection to server got closed. Server will restart.
[Error - 9:07:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=electron abi=93 uv=1 armv=8 libc=glibc node=16.14.2
    loaded from: /root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher

    at Function.load.resolve.load.path (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.vscode-server/extensions/nrwl.angular-console-17.28.2/nxls/main.js:213:9822)
[Error - 9:07:22 AM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:07:22 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:07:22 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 


```

**Comment by DromaderBosse** [comment]
> Exactly the same symptoms as @MartinPELCAT
> 
>     * Mac M1
> 
>     * OS: Ubuntu 22.04.1 LTS (Linux arm64 5.15.0-58-generic) (VM)
> 
>     * Node.js: 16.14.2
> 
>     * nx: 15.3.3
> 
>     * VSCode: 1.74.3

Just to complement, I tried:
1. manually installing libssl downloaded from https://ubuntu.pkgs.org/20.04/ubuntu-main-arm64/libssl1.1_1.1.1f-1ubuntu2_arm64.deb.html 
2. deleting my node-modules folder 
3. and doing a yarn --frozen-lockfile

But to no avail! Nx console still frozen.
Using the CLI, I have access to all the nx commands though (nx graph, nx serve, nx test, etc.).
So for the time being, that's what I'll content myself with.

**Comment by Cammisuli** [comment]
Hey all, we're still investigating ways around this issue. And I think I have a way to solve it. 

I'll keep this thread posted if the solution works.

**Comment by kmiqka** [comment]
If you use devcontainer (linux/arm64) as me on a MacBook M1/M2, then I have a small workaround based on https://github.com/nrwl/nx-console/issues/1440#issuecomment-1399751297.

Basically what I do is rebuilding the @parcel/watcher for the nx-console vscode extension.


If you'd like to use it through the vscode UI; you may add it to `.vscode/tasks.json` in your project folder:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build @parcel/watcher",
      "type": "shell",
      "command": "bash -c 'cd ~/.vscode-server/extensions/nrwl.angular-console-17.*/node_modules/@parcel/watcher && npm install && npm run prebuild'"
    }
  ]
}

```

After running the task, you should reload the window (Press CMD+Shift+P -> Reload Window) and the nx-console works.

If you don't want to add a vscode task, just run it in the devcontainer's terminal: `cd ~/.vscode-server/extensions/nrwl.angular-console-17.*/node_modules/@parcel/watcher && npm install && npm run prebuild` and reload window also works.

**Comment by AdamSundberg** [comment]
@kmiqka This may be a fix for some people. But for me this didn't work, check my comment above.

**Comment by bhuntay** [comment]
Had to pass in `--openssl_fips=''` to @kmiqka's script as mentioned here https://github.com/nodejs/node-gyp/issues/2673#issuecomment-1196931379 i.e. `d ~/.vscode-server/extensions/nrwl.angular-console-17.*/node_modules/@parcel/watcher && npm install --openssl_fips='' && npm run prebuild --openssl_fips=''`

**Comment by AdamSundberg** [comment]
@bhuntay This seems to also work for me. It is a temporary fix at least. Thank you!

**Comment by Cammisuli** [comment]
Linking this for my notes
https://github.com/parcel-bundler/watcher/issues/101

**Comment by drkfrtz** [comment]
Hi @Cammisuli, I would like to ask if there is any progress in solving this issue.

**Comment by Cammisuli** [comment]
We're still waiting for @parcel/watcher to include builds for linux arm64 instead of having people compile it themselves.

**Comment by brandonlang** [comment]
I am running into the same issue running on a Mac mini M2 but running Windows in Parallels.

```
Error: No native build was found for platform=win32 arch=arm64 runtime=electron abi=110 uv=1 armv=8 libc=glibc node=16.17.1 electron=22.5.7
    loaded from: c:\Users\brandon\.vscode\extensions\nrwl.angular-console-18.2.1\node_modules\@parcel\watcher

    at load.resolve.load.path (c:\Users\brandon\.vscode\extensions\nrwl.angular-console-18.2.1\node_modules\node-gyp-build\node-gyp-build.js:60:9)
    at load (c:\Users\brandon\.vscode\extensions\nrwl.angular-console-18.2.1\node_modules\node-gyp-build\node-gyp-build.js:22:30)
    at Object.<anonymous> (c:\Users\brandon\.vscode\extensions\nrwl.angular-console-18.2.1\node_modules\@parcel\watcher\index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
[Error - 8:37:07 AM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:37:07 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:37:07 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:37:07 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Running `npm i` I get the following folders. Is there a way to get a prebuild for win32-arm64?

![image](https://github.com/nrwl/nx-console/assets/908871/887294d5-d768-4b2d-9f75-f2aac0ddae04)

**Comment by kylebjordahl** [comment]
If, like me, you're looking for a quick patch, [this solution](https://github.com/nrwl/nx-console/issues/1440#issuecomment-1414283960) still works (M1 mac with an Ubuntu arm64 container) but with a small change now that the extension has bumped to v18 (got very confused why I couldn't `cd` into the package)

> cd ~/.vscode-server/extensions/nrwl.angular-console-17.*/node_modules/@parcel/watcher && npm install --openssl_fips='' && npm run prebuild --openssl_fips=''

`cd ~/.vscode-server/extensions/nrwl.angular-console-*/node_modules/@parcel/watcher && npm install --openssl_fips='' && npm run prebuild --openssl_fips=''`

**Comment by guillempuche** [comment]
@Cammisuli, issue fixed https://github.com/parcel-bundler/watcher/issues/101#issuecomment-1616341105
