### ISSUE TITLE
Command 'Nx: Remove Nx Project...' resulted in an error (Cannot read properties of undefined (reading 'toString'))

### ISSUE THREAD

**Issue by peterblazejewicz** [nrwl/nx-console#1545]
## Current Behavior

NX > Remove NX Project

throws error:

> Command 'Nx: Remove Nx Project...' resulted in an error (Cannot read properties of undefined (reading 'toString'))

## Expected Behavior

Command does succeed and NX asks for a project to remove

## Steps to Reproduce

1. Install NX extension (NX Console) in VSCode
2. create default NX workspace projects with at least two projects
3. open VSCode menu (CMD+SHIFT+P) and type 'Remove project'
4. select 'NX > remove NX project'

### Failure Logs / Images / Videos

> 2023-02-18 23:23:24.017 [error] TypeError: Cannot read properties of undefined (reading 'toString')
    at /Users/{USER}/.vscode/extensions/nrwl.angular-console-17.31.0/main.js:264:4955
    at s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108016)
    at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108744)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) nx.remove.fileexplorer {"value":"nrwl.angular-console","c":"nrwl.angular-console"}

### Environment

Node : 18.14.0
   OS   : darwin arm64
   npm  : 9.5.0

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4

- Nx Console version: 17.31.0
- VSCode version: Version: 1.75.1

**Comment by MaxKless** [comment]
Thanks for the report. This is my bad, because of the action naming I never really considered someone would run them from the command prompt instead of the file explorer context menu. 

A PR with the fix is up, should be merged and released quite soon.

**Comment by peterblazejewicz** [comment]
No worries, I'm using command palette mostly (or cli).
