### ISSUE TITLE
[Intellij] Nx Console-> Generate Ui fails when Nx workspace is not at root of the project opened in IntelliJ

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx-console#1560]
I have project with the following folder structures

<root_folder> //root folder that is opened in Intellij
	|--servers
    |----java-projet1
    |----java-projet2
	|--clients  // root for the Nx workspace
    |----apps/
    |----libs/
    |----node_modules/
    |----nx.json
## Current Behavior

Where trying to "Nx Generate Ui"  from a folder withinfails, because Nx is looking for the `node_modules` from ``

## Expected Behavior
Possible solutions:

- The plugin should find the closest `node_modules/` from which the command `Nx  Generate Ui`   was launched from
-  or Add a option in the Settings to set the location of  `node_modules` to use to access Nx
- 

### Failure Logs / Images / Videos

The stack trace from Intellij:

```
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: ENOENT: no such file or directory, stat 'D:\Workspace\git\zinniat-system\node_modules'
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$6$lambda$5(NxlsWrapper.kt:75)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Environment

 Nx Report
```
   Node : 14.21.1
   OS   : win32 x64
   npm  : 8.16.0

   nx : 15.1.0
   @nrwl/angular : 15.1.0
   @nrwl/cypress : 15.1.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.0
   @nrwl/js : 15.1.0
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.0
   @nrwl/workspace : 15.1.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.11.1
         @nebular/theme: 9.0.3
         @ngrx/effects: 14.0.2
         @ngrx/router-store: 14.0.2
         @ngrx/store: 14.0.2
         @ngrx/schematics: 14.0.2
         @ngrx/store-devtools: 14.0.2
         @storybook/angular: 6.5.13
```

- Nx Console version: 1.1.1
- Intellij version:  2022.3.2

**Comment by Cammisuli** [comment]
In the VSCode extension we did have a way to provide an alternate directory to set as the workspace, but that's not present currently in the intellij plugin.

We'll have to add this in eventually. The core already supports changing the workspace root, so we just need to add a settings page for Nx Console in Intellij.

**Comment by MaxKless** [comment]
Draft PR is up to enable this: https://github.com/nrwl/nx-console/pull/1569

Will be merged soon.
