### ISSUE TITLE
[IntelliJ] Webstorm plugin crashes with IllegalStateException: Missing header Content-Length in input " "

### ISSUE THREAD

**Issue by jase88** [nrwl/nx-console#1617]
## Current Behavior

Plugin crashes with `java.lang.IllegalStateException: Missing header Content-Length in input "`

## Expected Behavior

plugin is stable and does not crash ;) Don't know if it is an regression, because I'm a new user.

## Steps to Reproduce

I have not been able to see a pattern of exactly when this happens. Once it occurred after a branch change and this time only a badge icon was visible in the footer with the hint that the plugin crashed

### Failure Logs / Images / Videos

```
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Environment
- Windows within restricted network corporate environment
- Using new UI within WebStorm

```
 Node : 18.14.0                                           
   OS   : win32 x64                                         
   npm  : 9.5.0                                             
                                                            
   nx                      : 15.8.6                         
   @nrwl/js                : 15.8.6                         
   @nrwl/jest              : 15.8.6                         
   @nrwl/linter            : 15.8.6                         
   @nrwl/workspace         : 15.8.6                         
   @nrwl/angular           : 15.8.6                         
   @nrwl/cli               : 15.8.6                         
   @nrwl/cypress           : 15.8.6                         
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco : 4.2.6
   ng-mocks          : 14.7.1
   nx-stylelint      : 15.0.0
```

- Nx Console version: 1.2.0
- WebStorm 2022.3.3 (Build #WS-223.8836.27, built on March 1, 2023)

**Comment by MaxKless** [comment]
Hey @jase88! I've seen this error too. DId you try doing anything else with the plugin afterwards or was it completely broken?

**Comment by MaxKless** [comment]
yes next time it happens could you enable trace logging?

In the running instance of intellij: help > diagnostic tools > debug log settings then paste #dev.nx.console:trace

and then send over the logs so we can have a look :)

**Comment by MaxKless** [comment]
Just got this again when I had some errors in a `project.json` file. It looks like the daemon crashed because of it and while sending the error messages (line by line), the error occured:

<details>
<summary>Error messages</summary>

```
2023-03-20 10:09:27,900 [ 124827] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "
"
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,901 [ 124828] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
java.lang.IllegalStateException: Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,901 [ 124828] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
java.lang.IllegalStateException: Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,902 [ 124829] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "
"
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,902 [ 124829] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
java.lang.IllegalStateException: Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,903 [ 124830] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
java.lang.IllegalStateException: Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,903 [ 124830] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "
"
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,903 [ 124830] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
java.lang.IllegalStateException: Missing header Content-Length in input " >  NX   Daemon process terminated and closed the connection

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-20 10:09:27,903 [ 124830] SEVERE - org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer - Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
java.lang.IllegalStateException: Missing header Content-Length in input "   Please rerun the command, which will restart the daemon.

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by sjlehn** [comment]
I'm still getting this error in NxConsole 1.15.1, running PHPStorm 2023.2.3 on an M1 Mac running MacOS Sonoma 14.0
```
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
It happens every time I open the project. The plugin still seems to work, though.

**Comment by jvskriubakken** [comment]
I also got this exception in Nx Console 1.20.0 (Rider)
```

java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by MaxKless** [comment]
This will be fixed once and for all with https://github.com/nrwl/nx-console/pull/2067

**Comment by jvskriubakken** [comment]
Great!

**Comment by angelozerr** [comment]
@MaxKless I have the same issue with LSP4IJ, could you please explain me how you have fixed the problem? Is it a problem from LSP server side or LSP client side? Thanks for your help!

**Comment by MaxKless** [comment]
@angelozerr what this means is that the LSP is writing some things to `stdout` that aren't actual `JSON-RPC` messages. Maybe you have a console.log in there somewhere. Lsp4J will error in that case. I fixed it by monkey patching stdout to only allow messages that conform to the `JSON-RPC` format.

```export function ensureOnlyJsonRpcStdout() {
  process.stdout.write = ((
    chunk: any,
    encodingOrCallback?: any,
    callback?: any
  ) => {
    const message = chunk.toString();

    if (
      !message.startsWith('Content-Length:') &&
      !message.startsWith('{"jsonrpc":"2.0"')
    ) {
      return;
    }

    const originalWrite = process.stdout.constructor.prototype.write.bind(
      process.stdout
    );
    return originalWrite(chunk, encodingOrCallback, callback);
  }) as typeof process.stdout.write;
}```
