### ISSUE TITLE
[IntelliJ] Webstorm plugin crashes if opening.nx.json: Can't remove document listener

### ISSUE THREAD

**Issue by jase88** [nrwl/nx-console#1618]
## Current Behavior

plugin crashes if opening `nx.json`: Can't remove document listener

## Expected Behavior

plugins does not crash

## Steps to Reproduce

- open `nx.json` within WebStorm with plugin activated

### Failure Logs / Images / Videos

```
java.lang.Throwable: Can't remove document listener (dev.nx.console.nxls.managers.DocumentManager$documentListener$1@2e224176). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@bbd71b7, 305, 0, Multicaster, 49, 63, 42, 1, 10, 29, 48, 109, 11, 0, 0, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@e66584b, com.intellij.openapi.editor.impl.view.TextLayoutCache@4982460, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.LayeredLexer): '{
  "implicitDependencies": {
    ".stylelintrc.json": "*"
  },
  "npmScope": "company",
  "affected": {
    "defaultBase": "develop"
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/.eslintrc.json"
    ],
    "sharedGlobals": []
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    },
    "e2e": {
      "inputs": ["default", "^production"]
    },
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
    }
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e", "stylelint"]
      }
    }
  },
  "generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "project-web"
}
', 
use soft wraps: false, tab width: 4, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 1736, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@53a1bafd, com.intellij.openapi.editor.impl.CaretModelImpl@17e08e7f, com.intellij.openapi.editor.impl.InlayModelImpl@6da504f, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@27b95a30, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@7e048bb, {}, com.intellij.openapi.editor.impl.ScrollingModelImpl$1@2271b5b9]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:1009)
	at dev.nx.console.nxls.managers.DocumentManager.removeDocumentListener(DocumentManager.kt:147)
	at dev.nx.console.nxls.managers.DocumentManager.documentClosed(DocumentManager.kt:132)
	at dev.nx.console.nxls.NxlsWrapper.disconnect(NxlsWrapper.kt:129)
	at dev.nx.console.services.NxlsService.removeDocument(NxlsService.kt:71)
	at dev.nx.console.listeners.NxEditorListener.editorReleased(NxEditorListener.kt:19)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$3(EditorFactoryImpl.java:224)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:35)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:224)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.java:128)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.java:99)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.java:150)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:243)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:231)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:51)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite(FileEditorManagerImpl.java:1866)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$lambda$11(EditorWindow.kt:556)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1904)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.kt:538)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFile$5(FileEditorManagerImpl.java:706)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:704)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:714)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$TabMouseListener.mouseReleased(EditorTabbedContainer.java:372)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

### Environment

- Using new UI within WebStorm

```
 Node : 18.14.0                                           
   OS   : win32 x64                                         
   npm  : 9.5.0                                             
                                                            
   nx                      : 15.8.6                         
   @nrwl/js                : 15.8.6                         
   @nrwl/jest              : 15.8.6                         
   @nrwl/linter            : 15.8.6                         
   @nrwl/workspace         : 15.8.6                         
   @nrwl/angular           : 15.8.6                         
   @nrwl/cli               : 15.8.6                         
   @nrwl/cypress           : 15.8.6                         
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco : 4.2.6
   ng-mocks          : 14.7.1
   nx-stylelint      : 15.0.0
```

- Nx Console version: 1.2.0
- WebStorm 2022.3.3 (Build #WS-223.8836.27, built on March 1, 2023)

**Comment by PatrykKuniczak** [comment]
@Cammisuli After last update(1.14.0), i have this error again, on macOS

```java.lang.Throwable: Can't remove document listener (dev.nx.console.nxls.managers.DocumentManager$documentListener$1@5e7c4e9a). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@659c9781, 25, 0, Multicaster, 43, 18, 3, 0, 11, 11, 4, 4, 1, 0, 0, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@724ee864, com.intellij.openapi.editor.impl.view.TextLayoutCache@32ae9775, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.LayeredLexer): '{
  "name": "project-name",
  "version": "2.0.0",
  "private": true,
  "main": "file-name",
  "license": "GNU",
  "type": "module",
  "devDependencies": {
    "del": "^7.1.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-cli": "^2.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-rename": "^2.0.0",
    "gulp-rollup": "^2.17.0",
    "gulp-sass": "^5.1.0",
    "gulp-uglify": "^3.0.2",
    "sass": "~1.64.2",
    "eslint": "^8.49.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-node": "^4.1.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^5.0.0",
    "@commitlint/cli": "^17.7.1",
    "@commitlint/config-conventional": "^17.7.0",
    "husky": "^8.0.3",
    "lint-staged": "^14.0.1",
    "prettier": "^3.0.3"
  },
  "scripts": {
    "postinstall": "husky install",
    "commitlint": "commitlint --edit",
    "lint": "eslint . --fix",
    "format": "prettier . --write"
  },
  "lint-staged": {
    "*.--write": "prettier --write",
    "*.js": "eslint --fix"
  }
}
', 
use soft wraps: false, tab width: 4, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 1434, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@2beda330, com.intellij.openapi.editor.impl.CaretModelImpl@3e7c94ad, com.intellij.openapi.editor.impl.InlayModelImpl@22ae091f, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@4fe5465e, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@c437aff, EditorMarkupModel for EditorImpl[file:///Applications/MAMP/Sites/wordpress/wp-content/plugins/wcagbyl4web/package.json], com.intellij.openapi.editor.impl.ScrollingModelImpl$1@74eccbdd, com.intellij.codeInsight.inline.completion.listeners.InlineCompletionDocumentListener@17a95d70, com.intellij.openapi.editor.impl.EditorComponentImpl$AccessibleEditorComponentImpl@2b1dc981]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:995)
	at dev.nx.console.nxls.managers.DocumentManager.removeDocumentListener(DocumentManager.kt:145)
	at dev.nx.console.nxls.managers.DocumentManager.documentClosed(DocumentManager.kt:130)
	at dev.nx.console.nxls.NxlsWrapper.disconnect(NxlsWrapper.kt:180)
	at dev.nx.console.services.NxlsService.removeDocument(NxlsService.kt:150)
	at dev.nx.console.listeners.NxEditorListener.editorReleased(NxEditorListener.kt:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$3(EditorFactoryImpl.java:244)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:244)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.kt:137)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.kt:126)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.kt:146)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:161)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:262)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:51)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1689)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:572)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.kt:550)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.kt:545)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.defaultCloseFile(EditorWindow.kt:981)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.doTrimSize(EditorWindow.kt:902)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.trimToSize(EditorWindow.kt:868)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setComposite$intellij_platform_ide_impl(EditorWindow.kt:333)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openInEdtImpl(FileEditorManagerImpl.kt:2136)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$openInEdtImpl(FileEditorManagerImpl.kt:121)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileInEdt$2$1.invokeSuspend(FileEditorManagerImpl.kt:2090)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.pumpEventsForHierarchy(PlatformTaskSupport.kt:379)
	at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.access$pumpEventsForHierarchy(PlatformTaskSupport.kt:1)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2.invoke(PlatformTaskSupport.kt:157)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2.invoke(PlatformTaskSupport.kt:135)
	at com.intellij.openapi.application.impl.ModalityKt.inModalContext(modality.kt:12)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:135)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.access$runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:41)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:123)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:119)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:94)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:119)
	at com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking(tasks.kt:167)
	at com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking(tasks.kt:99)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFile(FileEditorManagerImpl.kt:812)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.kt:157)
	at com.intellij.openapi.vcs.changes.VcsEditorTabFilesManager.openFile(VcsEditorTabFilesManager.kt:83)
	at com.intellij.openapi.vcs.changes.VcsEditorTabFilesManager.openFile(VcsEditorTabFilesManager.kt:63)
	at com.intellij.openapi.vcs.changes.EditorTabDiffPreviewManager.showDiffFile(EditorTabDiffPreviewManager.kt:37)
	at com.intellij.openapi.vcs.changes.EditorTabPreviewBase$Companion.openPreview(EditorTabPreview.kt:195)
	at com.intellij.openapi.vcs.changes.EditorTabPreviewBase.openPreviewEditor(EditorTabPreview.kt:161)
	at com.intellij.openapi.vcs.changes.EditorTabPreviewBase.performDiffAction(EditorTabPreview.kt:182)
	at com.intellij.openapi.vcs.changes.EditorTabPreviewBase.installDoubleClickHandler$lambda$4(EditorTabPreview.kt:100)
	at com.intellij.openapi.vcs.changes.ui.ChangesTreeHandlers$MyDoubleClickListener.onDoubleClick(ChangesTreeHandlers.kt:43)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:58)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:437)
	at com.intellij.openapi.vcs.changes.ui.ChangesListView.processMouseEvent(ChangesListView.java:362)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at com.intellij.openapi.vcs.changes.ui.ChangesTree.processEvent(ChangesTree.java:830)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by PatrykKuniczak** [comment]
Still ocurr, anybody relate? @Cammisuli

**Comment by Cammisuli** [comment]
@PatrykKuniczak can you give me the exact steps you did where you see this error?

**Comment by PatrykKuniczak** [comment]
> @PatrykKuniczak can you give me the exact steps you did where you see this error? 

IDN, cause it's ocurr ocassionally, e.g 2/3 times per 8h work, and IDE inform me about it

**Comment by jase88** [comment]
Also still happening here on MacOS 14.1.1 (Intel).
Reproducible for me by opening `package.json` and closing the tab. Crash happens every time

**Comment by Cammisuli** [comment]
@jase88 yes please. If its 100% reproducible for you, let me know the steps you took, what jetbrains editor (with its version) and hopefully I can reproduce it on my side. 

For context, I use CLion every day working on the main Nx repo; so I'm opening and closing a lot of package.json/project.json/nx.json files. I pretty much use the extension everyday and I cant reproduce this 😞

**Comment by jase88** [comment]
Ok, here: https://github.com/nrwl/nx-console/issues/1946
Maybe it is related to the fact that WebStorm listens on changes to `package.json` and offers `npm install` if something changed?
