### ISSUE TITLE
VSCode: Error notification after window open / refresh

### ISSUE THREAD

**Issue by forivall** [nrwl/nx-console#1660]
## Current Behavior

In VS Code, with the "Generate & Run Target" tree view open, I often see the error notification "Cannot read properties of undefined (reading 'sendRequest')" after reloading the VS Code window.

## Expected Behavior

There should not be an error

## Steps to Reproduce

Using https://github.com/forivall/nx-repro-local-plugin-issue

Open the project in VS Code, with Nx Console installed and the Generate & Run Target tree view visible. It might happen more consistently with nx console in the secondary side panel (defaults to the right hand side)

Select "Developer: Reload Window" from the Command Pallette, OR, select "Developer: Restart Extension Host"

The notification appears.

### Failure Logs / Images / Videos

With [some modifications to the extension to add logging lines](https://github.com/nrwl/nx-console/compare/vscode-v17.32.0...forivall:nx-console:chore/logging-lines), I get the following in the "Nx Console" output channel:

```
sendRequest: nx/workspace
client not initialized! Error: 
	at sendRequest (~/.vscode/extensions/nrwl.angular-console-17.32.0/main.js:2055:79)
	at getNxWorkspace (~/.vscode/extensions/nrwl.angular-console-17.32.0/main.js:4813:41)
	at getTargetNames (~/.vscode/extensions/nrwl.angular-console-17.32.0/main.js:4479:67)
	at commandList (~/.vscode/extensions/nrwl.angular-console-17.32.0/main.js:4439:48)
	at RunTargetTreeProvider.getChildren (~/.vscode/extensions/nrwl.angular-console-17.32.0/main.js:4559:62)
	at w.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:66301)
	at w.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:62718)
	at h.$getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:59201)
	at c.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11655)
	at c.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11373)
	at c.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:10454)
	at c.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9589)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:8220
	at E.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:16654
	at E.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:14780)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain.emit (node:domain:475:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
Initialized lsp client
sendRequest: nx/version
sendRequest: nx/version
sendRequest: nx/workspace
sendRequest: nx/workspace
```

From this, we see that the `RunTargetTreeProvider` tries to use the lsp client before `configureLspClient` has been called.

### Environment

- Nx Console version: 17.32.0
- VSCode version: 1.77.0

**Comment by Cammisuli** [comment]
Hmm interesting. Thanks for the detailed report! I'll take a deeper look

**Comment by Cammisuli** [comment]
This is harder to reproduce than it seems. I cant seem to get it to break. But I'll keep this open for the mean time.

**Comment by forivall** [comment]
I've added some new notes to the original that might help it reproduce more consistently:

> It might happen more consistently with nx console in the secondary side panel (defaults to the right hand side)

> OR, select "Developer: Restart Extension Host"

Especially with restart extension host, that basically always triggers it.

**Comment by Cammisuli** [comment]
Ok, the restart extension host throws the error for me now. Thanks!
