### ISSUE TITLE
Webstorm-Plugin throws errors

### ISSUE THREAD

**Issue by nidomiro** [nrwl/nx-console#1663]
## Current Behavior

after startup and during usage this exception occurs:
```
java.lang.Throwable: kotlin.Unit
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:210)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at dev.nx.console.telemetry.measurementProtocol.MeasurementProtocolService.post(MeasurementProtocolTelemetryService.kt:65)
	at dev.nx.console.telemetry.measurementProtocol.MeasurementProtocolService.access$post(MeasurementProtocolTelemetryService.kt:23)
	at dev.nx.console.telemetry.measurementProtocol.MeasurementProtocolService$post$1.invokeSuspend(MeasurementProtocolTelemetryService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

## Expected Behavior

no exception

## Steps to Reproduce

start Webstorm 

### Failure Logs / Images / Videos

see above

### Environment

- Nx Console version: 1.3.0
- Webstorm version: 
```
WebStorm 2023.1
Build #WS-231.8109.174, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    ide.mac.file.chooser.native=false

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.8109.217)
    com.github.lppedd.idea-conventional-commit (0.22.0)
    com.fwdekker.randomness (2.7.6)
    org.antlr.intellij.plugin (1.20)
    ru.sadv1r.ansible-vault-editor-idea-plugin (1.20)
    org.rust.lang (0.4.191.5293-231)
    org.toml.lang (231.8109.91)
    com.intellij.plugins.macoskeymap (231.7515.9)
    com.samvtran.plugins.macosforallkeymap (2.0.0)
    com.myoutdesk.tailwind_formatter (2.0.7)
    com.github.copilot (1.2.5.2507)
    org.jetbrains.idea.grammar (2022.3.1)
    org.jetbrains.plugins.stylus (231.8109.91)
    org.jetbrains.plugins.go-template (231.8109.91)
    com.khmelyuk.multirun (1.13)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.intellij.ideolog (203.0.30.0)
    String Manipulation (9.7.1)
    ir.msdehghan.plugins.ansible (0.92)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    intellij-clock (2.0.0)
    Key Promoter X (2023.1.0)
    org.antlr.jetbrains.st4plugin (0.9)
    com.1v0.dev.hugo-intellij-plugin (0.4.9)
    indent-rainbow.indent-rainbow (2.1.0)
    com.intellij.kubernetes (231.8109.91)
    ru.adelf.idea.dotenv (2023.1)
    org.asciidoctor.intellij.asciidoc (0.38.12)
    org.intellij.prisma (231.8109.91)
    de.timo_reymann.intellij-mjml-support (2.4.0)
    dev.nx.console (1.3.0)
    com.intellij.lang.jsgraphql (3.4.0)
    mdx.js (231.8109.91)
    deno (231.8109.91)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-231)
    zielu.gittoolbox (500.0.6+213)
    mobi.hsz.idea.gitignore (4.5.0)
    izhangzhihao.rainbow.brackets (2023.2.6)

```

**Comment by nidomiro** [comment]
now also this happened after switching branches:
```
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by nidomiro** [comment]
Also the performance of my IDE is very, very, very bad after enabling this plugin. Even things like context-menus load forever.

**Comment by Cammisuli** [comment]
I just fixed the context menu loading very slowly that was merged into master recently. The other issues I'll look into.

**Comment by Cammisuli** [comment]
I just released 1.3.1, let me know if you're still experiencing issues once thats available. 🙏🏼

**Comment by Cammisuli** [comment]
Can you enable debug tracing, and upload the idea.log here?

### Instructions
Go to **Help** > **Diagnostic Tools** > **Debug Log Settings**... and then insert `#dev.nx.console:trace` like so:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/4332460/231494618-481a338f-48b9-4c4a-beb8-6a6da0d98619.png">

Then reproduce the issue, and attach the idea.log file to this issue. You can find the idea.log file with these instructions:
[intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by nidomiro** [comment]
Sure, this was a fresh startup in an nx-workspace: [idea.log](https://github.com/nrwl/nx-console/files/11229215/idea.log)

**Comment by Cammisuli** [comment]
Do you block all connections to https://google-analytics.com?

**Comment by nidomiro** [comment]
yes🙈 I use a PiHole on my network. That explains this error.

Thanks for the fixes 👍
