### ISSUE TITLE
[Intellij] No match found on macos

### ISSUE THREAD

**Issue by oben01** [nrwl/nx-console#1668]
## Current Behavior

No match found when running nx console
<img width="389" alt="Capture d’écran 2023-04-09 à 02 06 54" src="https://user-images.githubusercontent.com/22369027/230747657-5af4941e-519f-49db-a48c-5671dc716a7b.png">

 

## Expected Behavior

to work

## Steps to Reproduce

could be produced on  https://github.com/Yadoms/yadoms-client/tree/feature/pluginsPage

### Failure Logs / Images / Videos

```
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$7$lambda$6(NxlsWrapper.kt:87)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at jdk.proxy7/jdk.proxy7.$Proxy179.initialize(Unknown Source)
	at dev.nx.console.nxls.NxlsWrapper.start(NxlsWrapper.kt:105)
	at dev.nx.console.services.NxlsService.start(NxlsService.kt:38)
	at dev.nx.console.ProjectPostStartup.execute(ProjectPostStartup.kt:18)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invokeSuspend(StartupManagerImpl.kt:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1.invokeSuspend(StartupManagerImpl.kt:253)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 20 more
```
### Environment

- Nx Console version: 1.3.1
- Inttelij version: IntelliJ IDEA 2023.1 (Ultimate Edition
- Platform : macos

**Comment by Cammisuli** [comment]
Did you get a notification in the bottom corner of the IDE? Usually if the language server cannot start, it means that the workspace was malformed (ie. the project.json files arent correct or something similar)

If you go to **Diagnostic Tools** > **Debug Log Settings** > And then add this `#dev.nx.console:trace`, we can see more details in the idea.log file once the error is triggered again.

**Comment by oben01** [comment]
@Cammisuli after an update of npm version from 14 to v18.4.0 and `nx reset` it seams to fix the problem I'll close it for know. Thank u 👍
