### ISSUE TITLE
Intellij Plugin throws error on startup

### ISSUE THREAD

**Issue by etkachev** [nrwl/nx-console#1669]
## Current Behavior

Opening the nx console tab from right side should not throw errors and should display workspace targets, etc.

I'm assuming this error might also be partly causing issue with custom workspace generators not opening the fields at all in the Generate UI? (I can create a separate issue if you think these issues are unrelated).

## Expected Behavior

Based on videos and updates, it seems like the nx console tab from right side should be opening up workspace info like targets, etc.

## Steps to Reproduce

1. When Opening the Intellij/Webstorm IDE, trying to open the right side Nx console tab throws error (stack trace below).
2. Also nothing shows up in the tab Nx Console tab that was opened.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/9970746/230993566-b82da11b-4c67-411f-8150-c5ac14220a25.png">

Also when opening the Nx Generate UI but for a custom workspace schematic, it doesn't seem to pick up the schema and show the different options to fill out. (not sure if it's related to the above). But this doesn't throw errors. Just doesn't populate the UI.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/9970746/230993343-b0103f29-cb46-4448-98f1-268c1a28c1ee.png">
<img width="1826" alt="image" src="https://user-images.githubusercontent.com/9970746/230993439-577e0a60-c80f-4502-b953-b73e7a387b6c.png">

 
### Failure Logs / Images / Videos

Error that is thrown by the Nx Console plugin:
```text
org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
### Environment

Nx version: "14.8.3"
Webstorm Nx Console: "1.3.1"
Webstorm: "2023.1"

- Nx Console version: "1.3.1"
- VSCode version:

**Comment by Cammisuli** [comment]
Is this workspace available for me to clone? Does this happen if you open the nx-examples repo?

**Comment by Cammisuli** [comment]
Also, if you enable the debug logs, that would help some more. 

Go to **Help** > **Diagnostic Tools** > **Debug Log Settings...** and then insert `#dev.nx.console:trace`

**Comment by petarblazevski** [comment]
Experiencing the same issue. The project that I am working on is not NX. It is an Angular CLI project. When I open the project, the issue above is thrown. And then I cannot close my editor. When I try to close the editor it gets stuck on the "Closing projects" window
![image](https://user-images.githubusercontent.com/1238314/231430295-1ed5df6e-4893-40e7-94d4-8c9d45c2f9e9.png)

Also, when I open a non NX project, I am getting the following message 
![image](https://user-images.githubusercontent.com/1238314/231431232-d8952150-7edc-4c1b-8f72-656bc144040a.png)

**Comment by Cammisuli** [comment]
@petarblazevski can you attach the idea.log file when you notice any of these issues?

You can find the instructions here:
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

Then upload the idea.log here.

**Comment by Cammisuli** [comment]
I believe this was caused by the same issue as #1677, so that should be fixed in an upcoming release.
