### ISSUE TITLE
No prebuild or local build of @parcel/watcher found

### ISSUE THREAD

**Issue by lemonCMS** [nrwl/nx-console#1808]
service initializing failes

To have a working nx console

## Steps to Reproduce
create a new workspace

`npx create-nx-workspace@latest`

### Failure Logs
```powershell
c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\nxls\main.js:775:21404)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 10:07:17 PM] Connection to server got closed. Server will restart.
[Error - 10:07:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Sending request nx/version failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\nxls\main.js:775:21404)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 10:07:17 PM] Connection to server got closed. Server will restart.
[Error - 10:07:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:17 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\nxls\main.js:775:21404)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 10:07:18 PM] Connection to server got closed. Server will restart.
[Error - 10:07:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\nxls\main.js:775:21404)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 10:07:18 PM] Connection to server got closed. Server will restart.
[Error - 10:07:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.4.0\nxls\main.js:775:21404)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Error - 10:07:18 PM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:07:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:07:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

### Environment

```
 Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.5.1
   
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/angular        : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
```

- Nx Console version: 18.4.0
- VSCode version: 1.79.2
- Windows 11 PRO 10.0.22621 Build 22621

**Comment by Cammisuli** [comment]
Very strange, I just gave this a shot and I couldn't reproduce it.
![image](https://github.com/nrwl/nx-console/assets/4332460/70717438-6d40-4520-a87c-af9cc08b89fe)

Can you try uninstalling the extension, then deleting the any leftovers for it? You can find a list of extensions and their leftovers in `%USERPROFILE%\.vscode\extensions`. Look for `nrwl.angular-console` and delete the folder (if it still exists after after uninstalling from the VSCode UI)

**Comment by devongovett** [comment]
Hi, I maintain `@parcel/watcher` and just came across this issue. We don't currently include a prebuild for 32-bit Windows. What hardware are you running on? I was not aware of any modern CPUs that are 32-bit rather than 64-bit.

**Comment by lemonCMS** [comment]
@devongovett gave the solution, i was running vscode 32bit. Installing the 64bit version fixed the problem.

**Comment by blittle** [comment]
@devongovett I'm seeing this same issue running on Windows 10 inside a parallels arm64 vm.
![image](https://github.com/nrwl/nx-console/assets/1566869/a00059f0-c77f-4eab-8b16-cede677f28a1)

**Comment by devongovett** [comment]
Is it possible that you accidentally installed the 32-bit version of node rather than the 64-bit one? Could you follow the steps here to see which version of windows you are running? https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d

**Comment by blittle** [comment]
Yep, that is the issue. Thank you.

**Comment by bradmarder** [comment]
@devongovett I can replicate this error in docker with just `ENV NODE_ENV production` using multiple different node images.

**Comment by devongovett** [comment]
@bradmarder did you follow the error message instructions? Does the package it printed exist, or is your platform not supported? If it is, then can you determine why it wasn't installed by your package manager (e.g. configured not to install optional dependencies)? I'll need more info if I am to help you further.

**Comment by bradmarder** [comment]
@devongovett Sorry, I should have been more clear. I'm attempting to run `parcel build` inside a docker container using the latest node image, and everything works perfectly *unless* I include the line `ENV NODE_ENV production`. I understand parcel already sets this variable according to the docs, so setting it in the docker file shouldn't be required, but still, this should not trigger this error.

**Comment by royteeuwen** [comment]
Started having the same issue here in a docker node:16 image on a kubernetes cluster, not sure if there is an easy fix?

**Comment by devongovett** [comment]
I suspect https://github.com/npm/cli/issues/4828

**Comment by sanjaymereddy** [comment]
@devongovett I get same errors on my windows machine when I installed the "Nx Console" extension. I verified that I'm using VS Code 64bit installed too. 
![image (4)](https://github.com/nrwl/nx-console/assets/33429313/91ebd201-f69a-4c46-9c00-47ce1d6cfd47)

**Comment by devongovett** [comment]
I'm not sure what I'm supposed to do if a package manager fails to install the dependencies correctly. The package clearly [exists](https://www.npmjs.com/package/@parcel/watcher-win32-x64). I don't know what package manager vscode uses, but if it is npm, then the above issue I linked is probably the place to report this.

**Comment by MaxKless** [comment]
@sanjaymereddy are you also using the 64 bit version of node?

**Comment by sanjaymereddy** [comment]
@MaxKless Yes, I'm using 64bit node
C:\Users>node -p "process.arch"
x64

**Comment by sarahec** [comment]
I think I've identified the root cause -- it's in @parcel/watcher and how it loads extensions. TL;dr it's computing the expected filename and has hardcoded its search path. But these assumptions don't work on every OS and the module isn't found.

(See [index.js in @parcel/watcher](https://github.com/parcel-bundler/watcher/blob/master/index.js))

Once I can build a stand-alone reproducible case, I'll file a bug and PR on watcher.

**Comment by sarahec** [comment]
> I think I've identified the root cause -- it's in @parcel/watcher and how it loads extensions. TL;dr the loading algorithm is too simple

The problem is stranger than that, and I suspect (hope) there's a straightforward fix. 

There are two different builds of parcel/watcher referenced in the yarn.lock and the newer watcher uses a different directory layout. Some  people are getting the old directory layout being used by the newer code (and, presumably, vice versa.) parcel/watcher's code creates a filepath and name, then loads the prebuild directly, so 2.2.0 will fail to load on the pre-2.2.0 layout.

## Mixed references

* `yarn.lock` references both `"@parcel/watcher": "2.0.4"` and `"@parcel/watcher": "2.2.0"`
* The master package.json references 2.2.0
* The packages under nx-console/apps/vscode-e2e/testworkspaces/ all reference 2.0.4

## The directories look different on systems that work vs. ones that fail

Failing systems have the 2.0.4 layout:

```sh
[sec@dervish:~/scratch/watcher-test]$ ls -la node_modules/@parcel/
total 20
drwxr-xr-x   3 sec users  4096 Aug 20 14:50 .
drwxr-xr-x 320 sec users 12288 Aug 20 14:50 ..
drwxr-xr-x   4 sec users  4096 Aug 20 14:50 watcher

[sec@dervish:~/scratch/watcher-test]$ ls -la node_modules/@parcel/watcher
total 48
drwxr-xr-x 4 sec users 4096 Aug 20 14:50 .
drwxr-xr-x 3 sec users 4096 Aug 20 14:50 ..
-rw-r--r-- 1 sec users 2102 Aug 20 14:50 binding.gyp
-rw-r--r-- 1 sec users 1078 Aug 20 14:50 index.d.ts
-rw-r--r-- 1 sec users 1051 Aug 20 14:50 index.js
-rw-r--r-- 1 sec users  949 Aug 20 14:50 index.js.flow
-rw-r--r-- 1 sec users 1077 Aug 20 14:50 LICENSE
-rw-r--r-- 1 sec users 1436 Aug 20 14:50 package.json
drwxr-xr-x 6 sec users 4096 Aug 20 14:50 prebuilds
-rw-r--r-- 1 sec users 6491 Aug 20 14:50 README.md
drwxr-xr-x 8 sec users 4096 Aug 20 14:50 src

[sec@dervish:~/scratch/watcher-test]$ ls -la node_modules/@parcel/watcher/prebuilds
total 24
drwxr-xr-x 6 sec users 4096 Aug 20 14:50 .
drwxr-xr-x 4 sec users 4096 Aug 20 14:50 ..
drwxr-xr-x 2 sec users 4096 Aug 20 14:50 darwin-arm64
drwxr-xr-x 2 sec users 4096 Aug 20 14:50 darwin-x64
drwxr-xr-x 2 sec users 4096 Aug 20 14:50 linux-x64
drwxr-xr-x 2 sec users 4096 Aug 20 14:50 win32-x64
```

Working systems have the 2.2.0 layout:

```
[sec@dervish:~/scratch/watcher-test]$ ls -la node_modules/@parcel/
total 28
drwxr-xr-x   5 sec users  4096 Aug 20 15:04 .
drwxr-xr-x 321 sec users 12288 Aug 20 15:04 ..
drwxr-xr-x   2 sec users  4096 Aug 20 15:04 watcher
drwxr-xr-x   2 sec users  4096 Aug 20 15:04 watcher-linux-x64-glibc
drwxr-xr-x   2 sec users  4096 Aug 20 15:04 watcher-linux-x64-musl
```

(Note that my test build only generated the two prebuilds it needs, but the .vsix download contains all the prebuilds. You can download it directly and unzip to confirm.)

## Recommendation

Update all dependencies to 2.2.0 and regenerate a lockfile with only one version in play

**Comment by sarahec** [comment]
Note: I deleted a comment that said conflicting directory layouts were to blame (pre-watcher 2.2.0 vs. post-2.2.0) since it's also failing with the correct directory layout and loading code. I'm still debugging this.

(But maybe bringing all versions of watcher to 2.2.0 and losing the duplicate in yarn.lock is still a good idea.)

**Comment by sanjaymereddy** [comment]
@sarahec Thank you for looking at this issue. Please let me know when there is a fix or if there is any work around that I can try to run the extensions.

**Comment by sarahec** [comment]
To set expectations: I'm a volunteer looking into this. It's becoming clear that `require` is looking in the wrong place for the extensions, and I don't know if it can be fixed on the nx-console side (in the language server) or will need a PR filed against watcher.

My current working hypothesis: VSCode extensions have their own node_modules, and vscode makes assumptions about where these will be installed. It's either vscode setting the wrong path for `require` or a working directory issue after the language server is launched in its own process (forked). 

My next step is to reproduce the bug in a code sample and have you all run it as well. That'll show what needs to happen to fix it.

**Comment by RupertBarrow** [comment]
I'm getting this same issue when building in Github Actions : 
```
> BABEL_ENV=parcel parcel build src/index.html --public-url .

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (/home/runner/work/app/app/node_modules/@parcel/watcher/index.js:23:13)
```

**Comment by RupertBarrow** [comment]
This might help :

Running in Github Actions, I decided to add a step to explicitly build `@parcel/watcher` so I now have :
```
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
          cache: "npm"
      - run: npm install
      - run: npm add --save-dev @parcel/watcher
      - run: npm run build
      - run: npx semantic-release
```

I got this error during the `npm run build` step :

```
> BABEL_ENV=parcel parcel build src/index.html --public-url .

Building...
🚨 Build failed.

@parcel/transformer-css: Could not resolve module 
"../lightningcss.linux-x64-gnu.node" from 
"/home/runner/work/app/app/node_modules/lightningcss/node/index.js"

  Error: Could not resolve module "../lightningcss.linux-x64-gnu.node" from 
  "/home/runner/work/app/app/node_modules/lightningcss/node/index.js"
      at NodePackageManager.resolveInternal 
  (/home/runner/work/app/app/node_modules/@parcel/package-manager/lib/index.js:3672:21)
      at NodePackageManager.resolveSync 
  (/home/runner/work/app/app/node_modules/@parcel/package-manager/lib/index.js:3567:29)
      at NodePackageManager.requireSync 
  (/home/runner/work/app/app/node_modules/@parcel/package-manager/lib/index.js:3394:33)
      at m.require 
  (/home/runner/work/app/app/node_modules/@parcel/package-manager/lib/index.js:3410:25)
      at require (node:internal/modules/helpers:130:18)
      at Object.<anonymous> 
  (/home/runner/work/app/app/node_modules/lightningcss/node/index.js:21:22)
      at Module._compile (node:internal/modules/cjs/loader:1241:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
      at Module.load (node:internal/modules/cjs/loader:1091:32)
      at NodePackageManager.load 
  (/home/runner/work/app/app/node_modules/@parcel/package-manager/lib/index.js:3423:15)
```

Clearly a path problem.
Maybe this will help @sarahec and/or @devongovett find the issue ?
