### ISSUE TITLE
Nx console makes my IDE freeze (so crash)

### ISSUE THREAD

**Issue by LouisLecouturier** [nrwl/nx-console#1815]
## Current Behavior

Sometimes, when I right click a folder or want to open the NX console, my IDE Freezes (JetBrains Webstorm).
I can't even quit my IDE, I have to shut it down trough task manager

## Expected Behavior

No freeze

### Failure Logs / Images / Videos

stacktrace.txt : 
```
Freeze in EDT for 45 seconds
IDE KILLED! Sampled time: 34200ms, sampling rate: 100ms, GC time: 103ms (0%), Class loading: 0%

com.intellij.diagnostic.Freeze
	at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.nx.console.generate.actions.NxGenerateUiAction.actionPerformed$lambda$0(NxGenerateUiAction.kt:32)
	at dev.nx.console.generate.actions.NxGenerateUiAction$$Lambda$8420/0x000000030260f490.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at dev.nx.console.generate.actions.NxGenerateUiAction.actionPerformed(NxGenerateUiAction.kt:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$8419/0x0000000303184c80.run(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:532)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:252)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$1(ActionPopupStep.java:229)
	at com.intellij.ui.popup.ActionPopupStep$$Lambda$8418/0x0000000303184a38.run(Unknown Source)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$17(AbstractPopup.java:1618)
	at com.intellij.ui.popup.AbstractPopup$$Lambda$7850/0x0000000302d4d198.run(Unknown Source)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:172)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$$Lambda$1657/0x000000030114d878.run(Unknown Source)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:187)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:153)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:168)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:162)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1616)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:391)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:290)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:273)
	at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:485)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:512)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:479)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:426)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:302)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:281)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:400)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:372)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:115)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:157)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:107)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:547)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueueKt$$Lambda$724/0x0000000300796cc0.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueue$$Lambda$723/0x00000003007965c8.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Environment

Nx report :
```
 Node   : 18.16.0
   OS     : darwin-arm64
   pnpm   : 8.6.6
   
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/nest           : 16.5.0
   @nx/next           : 16.5.0
   @nx/node           : 16.5.0
   @nx/react          : 16.5.0
   @nx/storybook      : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
```

I am on Macbook Pro M1 2021

- Nx Console version: 1.8.0
- Webstorm version: 2023.1.3, Build #WS-231.9161.29

**Comment by MaxKless** [comment]
Thanks for the report! 
I fixed some issues like this recently, I will look into this one as well.
Make sure to download the latest Nx Console version once it releases (should be later today) and see if that helps things already :)

**Comment by Mosnar** [comment]
Just wanted to share that I see this on both current versions of the IntelliJ and VSCode plugins. After about 30-45 minutes, both display similar symptoms:

IntelliJ:
- Right clicking a directory in file browser will stop working (just shows a spinner)
- CMD+N fails to show new file dialog
- Can't close project without force quitting

VSCode:
- NX actions (e.g. run, generate) in sidebar stop working (clicking them does nothing)

Let me know if there's anything I can provide that might be helpful!

**Comment by LouisLecouturier** [comment]
That's exactly what's happening on my IDE

**Comment by MaxKless** [comment]
Thanks for the reports. I think something is up with the LSP and it's dying after a while. 
I will adjust IntelliJ to make sure the freezes don't happen any more but we really need to look into a way to restart the lsp or something along those lines @Cammisuli 

In VSCode you can always just run reload window and it should work again though.

**Comment by StringKe** [comment]
This problem is encountered even in projects that are not nx.

When the plugin is disabled, there is no problem.

**Comment by MaxKless** [comment]
Have you encountered this problem on the newest version (1.10?)

**Comment by LouisLecouturier** [comment]
Everything is fixed ! Thanks a lot !
