### ISSUE TITLE
Nx Console Yarn PnP support

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx-console#1843]
## Current Behavior

The plugin doesn't recognize the workspace and is empty.

## Expected Behavior
It should work...

I am using an NX project with Yarn 3 PnP.

It works on a project with Yarn 3 without PnP.

## Steps to Reproduce
Have an NX project with Yarn 3 PnP setup.

### Failure Logs / Images / Videos

```ts
java.lang.Throwable: Can't remove document listener (dev.nx.console.nxls.managers.DocumentManager$documentListener$1@4110920e). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@52dea231, 144, 0, Multicaster, 36, 62, 83, 6, 38, 47, 89, 134, 12, 0, 0, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@4c5468cb, com.intellij.openapi.editor.impl.view.TextLayoutCache@48263c12, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.LayeredLexer): '{
  "name": "orchestrator-schema",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "generated",
  "projectType": "library",
  "targets": {
    "generateClient": {
      "executor": "nx:run-commands",
      "options": {
        "commands": ["yarn graphql-codegen --config libs/orchestrator-schema/codegen.ts"],
        "parallel": false
      }
    }
  },
  "tags": []
}
', 
use soft wraps: false, tab width: 2, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 2065, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@1563e73f, com.intellij.openapi.editor.impl.CaretModelImpl@5b0b4c01, com.intellij.openapi.editor.impl.InlayModelImpl@76e39f7c, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@7f38707, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@261ebcba, {}, com.intellij.openapi.editor.impl.ScrollingModelImpl$1@483d3587]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:1009)
	at dev.nx.console.nxls.managers.DocumentManager.removeDocumentListener(DocumentManager.kt:145)
	at dev.nx.console.nxls.managers.DocumentManager.documentClosed(DocumentManager.kt:130)
	at dev.nx.console.nxls.NxlsWrapper.disconnect(NxlsWrapper.kt:188)
	at dev.nx.console.services.NxlsService.removeDocument(NxlsService.kt:125)
	at dev.nx.console.listeners.NxEditorListener.editorReleased(NxEditorListener.kt:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$3(EditorFactoryImpl.java:245)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:245)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.kt:129)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.kt:113)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.java:149)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:51)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1660)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$closeFile$1.invoke(EditorWindow.kt:564)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$closeFile$1.invoke(EditorWindow.kt:546)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$Companion.runBulkTabChange$intellij_platform_ide_impl(FileEditorManagerImpl.kt:390)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:546)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl$default(EditorWindow.kt:545)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$lambda$12(FileEditorManagerImpl.kt:701)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$intellij_platform_ide_impl(FileEditorManagerImpl.kt:700)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.kt:708)
	at com.intellij.openapi.fileEditor.impl.tabActions.CloseTab.actionPerformed(CloseTab.kt:95)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:598)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
### Environment

   Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.1
   
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/react          : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6

- Nx Console version: 1.10.0
- Intellij Idea version: Build #IU-231.8770.65, built on April 27, 2023

**Comment by MaxKless** [comment]
Thanks for the report :) 
Right now, there's no Yarn PnP support in Nx Console, so this is to be expected. 
We'll talk about it internally, it will have to be supported at some point.
