### ISSUE TITLE
nx generate in Nx Console terminated with exit code 1

### ISSUE THREAD

**Issue by chriscurnow** [nrwl/nx-console#1857]
### Current Behavior

Every time I try to use nx Generate from Nx Console in VS Code I get an error similar to this:

Error: Cannot find module 'fs/promises'
Require stack:
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/daemon/client/client.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/project-graph/project-graph.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/generate/generate.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/generate/command-object.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/nx-commands.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/bin/init-local.js
- /Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module.Mod.require (/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/bin/init-local.js:204:36)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/daemon/client/client.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/daemon/client/client.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/project-graph/project-graph.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/generate/generate.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/generate/command-object.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/src/command-line/nx-commands.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/bin/init-local.js',
    '/Users/chriscurnow/Projects/4cast/workspace/node_modules/nx/bin/nx.js'
  ]
}

 *  The terminal process "/bin/zsh '-l', '-c', 'npx nx generate @angular/material:tree project-tree-line --project=shared-global-project-feature-project --path=libs/shared/global/project/feature-project/src/lib/project-select --no-interactive --dry-run'" terminated with exit code: 1. 

This has only started happening recently.

If I run the nx generate command from the terminal, it works fine.

### Expected Behavior

Nx generate generates to appropriate item.

### GitHub Repo

https://github.com/4Cast/workspace branch dv/114

### Steps to Reproduce

1. Right-click somewhere in the sidebar and select Nx generate...
2. Select a generator, eg @schematics/angular:component.
3. Type a name for the item to generate.

### Nx Report

```shell
Node   : 16.20.1
   OS     : darwin-x64
   npm    : 8.19.4
   
   nx (global)        : 16.5.5
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/angular        : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/plugin         : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/webpack        : 16.5.5
   nx-cloud           : 16.1.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.1
   @ngrx/effects         : 16.0.1
   @ngrx/entity          : 16.0.1
   @ngrx/router-store    : 16.0.1
   @ngrx/schematics      : 16.0.1
   @ngrx/store           : 16.0.1
   @ngrx/store-devtools  : 16.0.1
   @schematics/fourcast  : 1.0.2
   rxjs                  : 6.6.7
   ---------------------------------------
   Local workspace plugins:
         @workspace/workspace-plugin
         nx
         fc-ngrx
```

### Failure Logs

```shell
I'm sorry, I don't know which logs to look in to find anything relevant.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
What version of VSCode are you using?

Does this issue happen if you run the following steps?:
1) Close vscode
1) open a terminal
1) go to your workspace
1) run `nx daemon --stop`
1) confirm the daemon is stopped with `nx daemon`
1) run `nx daemon --start`
1) confirm that the daemon is running with `nx daemon`
1) open vscode
1) generate again

**Comment by jccrosby** [comment]
Created a new workspace with `16.7.4` and am getting a slightly different error now. 

`Error: Cannot find module 'node:path'`

MacOS Version 13.2 (22D49)
Node version: v18.17.1
NPM version: v9.6.7

Also tried with yarn 
Yarn version: v1.22.19

```
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
```

Full output:
```bash
 *  Executing task: npx nx generate @nx/react:application --name=test-app --no-interactive --dry-run 

nx generate <generator> [_..]

Generate or update source code (e.g., nx generate @nx/js:lib mylib).

Positionals:
  generator  Name of the generator (e.g., @nx/js:library, library)                                                                                                                                                  [string] [required]

Options:
      --version      Show version number                                                                                                                                                                                      [boolean]
  -d, --dryRun       Preview the changes without updating files                                                                                                                                              [boolean] [default: false]
      --interactive  When false disables interactive input prompts for options                                                                                                                                [boolean] [default: true]
      --verbose      Prints additional information about the commands (e.g., stack traces)                                                                                                                                    [boolean]
      --quiet        Hides logs from tree operations (e.g. `CREATE package.json`)                                                                                                                                             [boolean]

Error: Cannot find module 'node:path'
Require stack:
- /_projects/test/node_modules/nx/src/project-graph/utils/project-configuration-utils.js
- /_projects/test/node_modules/nx/src/project-graph/build-nodes/workspace-projects.js
- /_projects/test/node_modules/nx/src/project-graph/build-nodes/index.js
- /_projects/test/node_modules/nx/src/project-graph/build-project-graph.js
- /_projects/test/node_modules/nx/src/project-graph/project-graph.js
- /_projects/test/node_modules/nx/src/command-line/generate/generate.js
- /_projects/test/node_modules/nx/src/command-line/generate/command-object.js
- /_projects/test/node_modules/nx/src/command-line/nx-commands.js
- /_projects/test/node_modules/nx/bin/init-local.js
- /_projects/test/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.Mod.require (/_projects/test/node_modules/nx/bin/init-local.js:203:36)
    at require (/_projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/_projects/test/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:5:21)
    at Module._compile (/_projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/_projects/test/node_modules/nx/src/project-graph/utils/project-configuration-utils.js',
    '/_projects/test/node_modules/nx/src/project-graph/build-nodes/workspace-projects.js',
    '/_projects/test/node_modules/nx/src/project-graph/build-nodes/index.js',
    '/_projects/test/node_modules/nx/src/project-graph/build-project-graph.js',
    '/_projects/test/node_modules/nx/src/project-graph/project-graph.js',
    '/_projects/test/node_modules/nx/src/command-line/generate/generate.js',
    '/_projects/test/node_modules/nx/src/command-line/generate/command-object.js',
    '/_projects/test/node_modules/nx/src/command-line/nx-commands.js',
    '/_projects/test/node_modules/nx/bin/init-local.js',
    '/_projects/test/node_modules/nx/bin/nx.js'
  ]
}

 *  The terminal process "/usr/local/bin/zsh '-l', '-c', 'npx nx generate @nx/react:application --name=test-app --no-interactive --dry-run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

**Comment by Cammisuli** [comment]
hmm, now i think that it might be related to whatever version of Node is currently your default. We can check what version is used by creating this task within `.vscode/tasks.json` in your repo:
```
{
	"type":"shell", 
	"command": "node -v",
	"label": "node version"
}
```

Then running `cmd + p` > `task node version` and then see what version of Node comes up. If it's less than 16, then make sure to change the default node version. If it's 16+, we can think of something else.

**Comment by jccrosby** [comment]
There it is! 🎉  I was getting node `v12.22.1` when running the `node version` task. 

To fix it, I needed to add the following to the VS Code user settings for VS Code to pick up the default node version set by Volta/NVM in the [task/debug](https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile) profile.

```json
"terminal.integrated.automationProfile.osx": {
    "path": "/bin/zsh",
    "args": [
        "-i"
    ]
},
```

Once I did that I was able to run generators without issue.

**Comment by chriscurnow** [comment]
@MaxKless sorry to take so long to get back to you. I was lying in a hospital bed after breaking my hip in October last year.

YES, it does work for me👍🙏

**Comment by MaxKless** [comment]
Hope you feel better!

**Comment by chriscurnow** [comment]
Thanks,I am a lot better now - although my memory from around the time of the accident has been affected.I had completely forgotten I raised an identical issue in August last year.Fortunately it is only a minor memory loss and it seems to be gradually coming back.The brain is an amazing thing.Sent from my iPadOn 6 May 2024, at 6:15 PM, MaxKless ***@***.***> wrote:﻿
Hope you feel better!
