### ISSUE TITLE
client server not running and server initialization failed

### ISSUE THREAD

**Issue by MuchinaWamburia** [nrwl/nx-console#1891]
c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\nxls\main.js:776:25291)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 3:06:58 PM] Connection to server got closed. Server will restart.
[Error - 3:06:58 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:06:58 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:06:58 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:06:58 PM] Sending request nx/version failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:06:58 PM] Sending request nx/workspace failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\nxls\main.js:776:25291)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 3:07:13 PM] Connection to server got closed. Server will restart.
[Error - 3:07:13 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:13 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\nxls\main.js:776:25291)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 3:07:19 PM] Connection to server got closed. Server will restart.
[Error - 3:07:19 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:19 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:19 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\nxls\main.js:776:25291)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Info  - 3:07:21 PM] Connection to server got closed. Server will restart.
[Error - 3:07:21 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:21 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:21 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25
      throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);
      ^

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-ia32. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\Users\Admin\.vscode\extensions\nrwl.angular-console-18.8.1\nxls\main.js:776:25291)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Error - 3:07:22 PM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 3:07:22 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:22 PM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:07:22 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by MaxKless** [comment]
Hi @MuchinaWamburia thanks for reporting this. 
It looks like you're trying to install `@parcel/watcher-win32-ia32`. However, there are no 32-bit versions of `@parcel/watcher` and there isn't really much hardware around that runs 32 bit systems anymore? 
What kind of hardware are you running on? Please include a paste of `nx report` in the issue. 

Are you sure you have the right version of VSCode installed? 64 bit instead of 32 bit?

**Comment by mrvonwyl** [comment]
I get pretty much the same error. I am in a corporate environment which is pretty isolated. There is no direct internet access. However the public npm repository is available. I use NX Console 18.10.1.

My Windows and VS Code is x64. It is a citrix VM.

```
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-win32-x64. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (c:\Users\p21443\.vscode\extensions\nrwl.angular-console-18.10.1\node_modules\@parcel\watcher\index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (c:\Users\p21443\.vscode\extensions\nrwl.angular-console-18.10.1\nxls\main.js:776:26973)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)

Node.js v18.15.0
[Error - 10:30:25 AM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:30:25 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:30:25 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:30:25 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

nx report:
```
 >  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : win32-x64
   npm    : 8.19.2

   nx (global)        : 17.1.2
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/plugin         : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngneat/transloco : 6.0.0
   ---------------------------------------
   Local workspace plugins:
         @leistung-rp/docker
```

Reopening this issue would be greatly appreciated.
