### ISSUE TITLE
IntelliJ IDEA Nx Plugin not working on Windows because "java.lang.AssertionError: Linux path was expected, but got ..."

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx-console#1920]
## Current Behavior

Pressing the run config button leads to an error and a loading circle that **won't disappear again** in the IDE's menu

![image](https://github.com/nrwl/nx-console/assets/1553757/d65e98d8-f14a-4780-be9b-b7bca4ae9b98)

## Steps to Reproduce

I've installed the plugin and created a run configuration with

![image](https://github.com/nrwl/nx-console/assets/1553757/5f9b2328-c1a4-496f-8bea-86f0a31ffd78)

The config shows the correct Windows path

![image](https://github.com/nrwl/nx-console/assets/1553757/aeb4e718-a874-4308-a913-147d5378631a)

### Failure Logs / Images / Videos

```
java.lang.AssertionError: Linux path was expected, but got C:/Users/user/Workspace/my-project
	at com.intellij.execution.wsl.WSLCommandLineOptions.setRemoteWorkingDirectory(WSLCommandLineOptions.java:129)
	at com.intellij.execution.wsl.target.WslTargetEnvironment.createProcess(WslTargetEnvironment.kt:120)
	at com.intellij.javascript.nodejs.execution.NodeTargetRun.startProcessEx(NodeTargetRun.kt:185)
	at com.intellij.javascript.nodejs.execution.NodeTargetRun.startProcess(NodeTargetRun.kt:103)
	at dev.nx.console.run.NxCommandLineState.startProcess(NxCommandLineState.kt:96)
	at com.intellij.javascript.nodejs.execution.NodeBaseRunProfileState$Companion.runInBackground(NodeBaseRunProfileState.kt:57)
	at com.intellij.javascript.nodejs.execution.NodeBaseRunProfileState$Companion.access$runInBackground(NodeBaseRunProfileState.kt:40)
	at com.intellij.javascript.nodejs.execution.NodeBaseRunProfileState$Companion$executeUnderProgress$1.run(NodeBaseRunProfileState.kt:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:477)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Environment

- Nx Console version:
- VSCode version:

**Comment by MaxKless** [comment]
sorry, this completely fell under the radar. is this still happening?
Are you running IntelliJ through WSL?
