### ISSUE TITLE
v18.10.0 not loading UI on windows

### ISSUE THREAD

**Issue by stephen-moyer** [nrwl/nx-console#1924]
## Current Behavior
The console UI does not load on v18.10.0, it just shows the "Getting started" button. The extension host log shows an error loading `@nx/nx-win32-x64-msvc`

Reverting to v18.9.0 works as expected.

## Expected Behavior
The console UI to load.

## Steps to Reproduce
Update to v18.10.0 of the extension

### Failure Logs / Images / Videos
Full error from vscode extension log:
```
2023-11-06 10:08:45.243 [error] Activating extension nrwl.angular-console failed due to an error:
2023-11-06 10:08:45.243 [error] Error: Cannot find module '@nx/nx-win32-x64-msvc'
Require stack:
- c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js
- c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2786)
	at Module._load (node:internal/modules/cjs/loader:974:27)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:200988:23
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:235508:11
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:236066:11
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:236531:11
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:236927:13
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:237323:13
	at c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:8:32
	at Object.<anonymous> (c:\Users\smoyer\.vscode\extensions\nrwl.angular-console-18.10.0\main.js:258089:14)
	at o._compile (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at h.vb (c:\Users\smoyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:30610)
	at async Promise.all (index 0)
```

### Environment
Windows 11.

- Nx Console version: v18.10.0
- VSCode version: v1.84.0
- Node version: 20.9.0

Coworkers are experiencing the same thing on node 18 as well.

**Comment by admin-sogitec** [comment]
Whats happen??? dont work anymore?

**Comment by labeled** [comment]
Same issue here on windows, latest 18.10.0 no longer shows the list of libs and apps. Only difference is we're on node 16.17.0

**Comment by Cammisuli** [comment]
Sorry folks, it was a bad release. There were some additional dependencies that slipped my mind. I'm going to push a new release soon.
