### ISSUE TITLE
WebStorm crashes on closing package.json: java.lang.Throwable: Can't remove document listener

### ISSUE THREAD

**Issue by jase88** [nrwl/nx-console#1946]
## Current Behavior
- Nx plugin crashes if closing a `package.json`
  - this happens for nx workspaces, but also on Angular CLI projects without nx 

## Expected Behavior
- no crash if closing `package.json` within a project

## Steps to Reproduce

- create a nx workspace (with the given dependencies)
- open `package.json`
- close `package.json`

this is always reproducible on my Intel Mac. Let me know if I can somehow help!

### Failure Logs / Images / Videos

```
java.lang.Throwable: Can't remove document listener (dev.nx.console.nxls.managers.DocumentManager$documentListener$1@b116c9d). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@6b6543d4, 1, 0, Multicaster, 0, 28, 0, 0, 7, 25, 7, 4, 1, 0, 0, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@2e9c0049, com.intellij.openapi.editor.impl.view.TextLayoutCache@cce770e, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.LayeredLexer): '{
  "name": "my-project",
  "version": "0.0.0-package",
  "engines": {
    "npm": ">=9",
    "node": ">=18"
  },
  "private": true,
  "scripts": {
    "prepare": "cd .. && husky install web/.husky",
    "start": "npm run prebuild && ng serve",
    "build-raw": "npm run build -- --configuration=raw",
    "lint:fix": "npm run prebuild && ng lint --fix",
    "lint": "eslint --format gitlab .",
    "stylelint": "stylelint \"src/**/*.scss\"",
    "stylelint:fix": "npm run stylelint -- --fix",
    "format": "prettier --write .",
    "format:check": "prettier --check .",
    "test": "npm run prebuild && jest",
    "test:ci": "npm run prebuild && jest --runInBand",
    "e2e": "playwright test",
    "e2e:ui": "npm run e2e -- --ui",
    "audit": "npm audit --omit=dev",
    "generate-bom": "cyclonedx-npm --output-file ./src/bom.json --omit dev --flatten-components --short-PURLs",
    "i18n-update-locales": "ngx-translate-extract --input ./src --output ./src/locales/*.json --clean --sort --format-indentation '  ' --format namespaced-json",
    "check:locales": "ts-node --project tsconfig.scripts.json ./scripts/check-locales.ts",
    "i18n-test-files": "ngx-translate-extract --input ./src --output ./src/locales/test.json --clean --sort --format namespaced-json --format-indentation '  ' && npm run check:locales",
    "ng": "ng",
    "build": "ng build",
    "serve:dev": "npx angular-http-server -p 3000 --path ./dist/dev --silent",
    "prebuild": "ts-node --project tsconfig.scripts.json ./scripts/prebuild.ts"
  },
  "dependencies": {
    "@angular/animations": "16.2.12",
    "@angular/cdk": "16.2.12",
    "@angular/common": "16.2.12",
    "@angular/compiler": "16.2.12",
    "@angular/core": "16.2.12",
    "@angular/forms": "16.2.12",
    "@angular/material": "16.2.12",
    "@angular/platform-browser": "16.2.12",
    "@angular/platform-browser-dynamic": "16.2.12",
    "@angular/router": "16.2.12",
    "@ngx-translate/core": "15.0.0",
    "@ngx-translate/http-loader": "8.0.0",
    "@ngxs/form-plugin": "3.8.1",
    "@ngxs/router-plugin": "3.8.1",
    "@ngxs/storage-plugin": "3.8.1",
    "@ngxs/store": "3.8.1",
    "angular-oauth2-oidc": "15.0.1",
    "angularx-qrcode": "16.0.2",
    "chart.js": "4.4.0",
    "chartjs-plugin-datalabels": "2.2.0",
    "d3-selection": "3.0.0",
    "d3-zoom": "3.0.0",
    "dompurify": "3.0.6",
    "fast-deep-equal": "3.1.3",
    "file-saver": "2.0.5",
    "luxon": "3.4.4",
    "maplibre-gl": "3.5.2",
    "material-icons": "1.13.12",
    "ng2-charts": "5.0.3",
    "ngx-tippy-wrapper": "6.2.2",
    "roboto-fontface": "0.10.0",
    "rxjs": "7.8.1",
    "tslib": "2.6.2",
    "uuid": "9.0.1",
    "zone.js": "0.13.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "16.2.10",
    "@angular-eslint/builder": "16.3.1",
    "@angular-eslint/eslint-plugin": "16.3.1",
    "@angular-eslint/eslint-plugin-template": "16.3.1",
    "@angular-eslint/schematics": "16.3.1",
    "@angular-eslint/template-parser": "16.3.1",
    "@angular/cli": "16.2.10",
    "@angular/compiler-cli": "16.2.12",
    "@compodoc/compodoc": "1.1.22",
    "@cyclonedx/cyclonedx-npm": "1.14.2",
    "@ngxs/devtools-plugin": "3.8.1",
    "@ngxs/logger-plugin": "3.8.1",
    "@playwright/test": "1.39.0",
    "@storybook/addon-a11y": "7.5.3",
    "@storybook/addon-designs": "7.0.5",
    "@storybook/addon-essentials": "7.5.3",
    "@storybook/addon-interactions": "7.5.3",
    "@storybook/addon-links": "7.5.3",
    "@storybook/addon-viewport": "7.5.3",
    "@storybook/angular": "7.5.3",
    "@storybook/blocks": "7.5.3",
    "@storybook/jest": "0.2.3",
    "@storybook/testing-library": "0.2.2",
    "@trivago/prettier-plugin-sort-imports": "4.3.0",
    "@types/dompurify": "3.0.5",
    "@types/jest": "29.5.8",
    "@types/luxon": "3.3.4",
    "@types/node": "20.9.0",
    "@typescript-eslint/eslint-plugin": "6.10.0",
    "@typescript-eslint/parser": "6.10.0",
    "@vendure/ngx-translate-extract": "8.2.3",
    "dpdm": "3.14.0",
    "eslint": "8.53.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-formatter-gitlab": "5.1.0",
    "eslint-plugin-etc": "2.0.3",
    "eslint-plugin-import": "2.29.0",
    "eslint-plugin-jest": "27.6.0",
    "eslint-plugin-no-unsanitized": "4.0.2",
    "eslint-plugin-playwright": "0.18.0",
    "eslint-plugin-rxjs": "5.0.3",
    "eslint-plugin-sonarjs": "0.23.0",
    "eslint-plugin-storybook": "0.6.15",
    "eslint-plugin-unicorn": "49.0.0",
    "husky": "8.0.3",
    "jest": "29.7.0",
    "jest-fail-on-console": "3.1.1",
    "jest-junit": "16.0.0",
    "jest-preset-angular": "13.1.4",
    "lint-staged": "15.1.0",
    "ng-mocks": "14.11.0",
    "postcss": "8.4.31",
    "prettier": "3.0.3",
    "storybook": "7.5.3",
    "storybook-dark-mode": "3.0.1",
    "stylelint": "15.11.0",
    "stylelint-config-standard": "34.0.0",
    "stylelint-config-standard-scss": "11.1.0",
    "tailwindcss": "3.3.5",
    "ts-node": "10.9.1",
    "typescript": "5.1.6",
    "typescript-json-schema": "0.62.0"
  }
}
',
use soft wraps: false, tab width: 2, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 1931, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@82a4484, com.intellij.openapi.editor.impl.CaretModelImpl@1050b612, com.intellij.openapi.editor.impl.InlayModelImpl@6bf24636, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@2c540d61, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@29a1b931, EditorMarkupModel for EditorImpl[file:///Users/user/src/my-project/package.json], com.intellij.openapi.editor.impl.ScrollingModelImpl$1@6c4abb71, com.intellij.codeInsight.inline.completion.listeners.InlineCompletionDocumentListener@6c3f57e1, com.intellij.openapi.editor.impl.EditorComponentImpl$AccessibleEditorComponentImpl@600c7002]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:995)
	at dev.nx.console.nxls.managers.DocumentManager.removeDocumentListener(DocumentManager.kt:145)
	at dev.nx.console.nxls.managers.DocumentManager.documentClosed(DocumentManager.kt:130)
	at dev.nx.console.nxls.NxlsWrapper.disconnect(NxlsWrapper.kt:180)
	at dev.nx.console.services.NxlsService.removeDocument(NxlsService.kt:150)
	at dev.nx.console.listeners.NxEditorListener.editorReleased(NxEditorListener.kt:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$3(EditorFactoryImpl.java:244)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:244)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.kt:137)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.kt:126)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.kt:146)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:161)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:262)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:51)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1689)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:572)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl$default(EditorWindow.kt:553)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$intellij_platform_ide_impl(FileEditorManagerImpl.kt:699)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.kt:720)
	at com.intellij.openapi.fileEditor.impl.tabActions.CloseTab.actionPerformed(CloseTab.kt:101)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.ui.tabs.impl.ActionButton.actionPerformed(ActionButton.java:138)
	at com.intellij.ui.InplaceButton.doClick(InplaceButton.java:92)
	at com.intellij.ui.InplaceButton$1.execute(InplaceButton.java:53)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:213)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:195)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
### Environment

   Node   : 20.9.0
   OS     : darwin-x64
   npm    : 10.2.4

- Nx Console version: 1.15.1
- WebStorm version: 2023.2.5

**Comment by Den-dp** [comment]
I noticed this even in non-nx projects:

```
md foo
cd foo
npm init -y
webstorm .
# now open and close package.json
```
![image](https://github.com/nrwl/nx-console/assets/1770529/b3eb940b-c2c1-4876-b0ef-97f98f64b54e)

**Comment by MaxKless** [comment]
Hey! Sorry but I haven't managed to repro this bug, even though I see it in different logs from people.
I put up a PR with what I think might be a fix: https://github.com/nrwl/nx-console/pull/1960
would be happy to see if it works once it's released.

**Comment by jase88** [comment]
Great hopefully it will be solved.

Would it help if we test some kind of preview version or will there be a release soon anyway?

**Comment by tsopeh** [comment]
Hope this gets resolved soon 🤞

<details>

 <summary>Error log</summary>

```
java.lang.Throwable: Can't remove document listener (dev.nx.console.nxls.managers.DocumentManager$documentListener$1@6b216e25). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@663e33ff, 0, 0, Multicaster, 137, 27, 7, 0, 17, 2, 32, 4, 1, 0, 0, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@599b6378, com.intellij.openapi.editor.impl.view.TextLayoutCache@385198ad, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.LayeredLexer): '

I HAVE TO OMIT PACKAGE JSON CONTENT

', 
use soft wraps: false, tab width: 4, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 1418, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@10482484, com.intellij.openapi.editor.impl.CaretModelImpl@36ae6bdd, com.intellij.openapi.editor.impl.InlayModelImpl@76846d6a, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@664c4844, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@29a6175c, com.intellij.openapi.editor.impl.ScrollingModelImpl$1@4916140b, EditorMarkupModel for EditorImpl[file:///Users/petar/p/webclient/package.json], com.intellij.codeInsight.inline.completion.listeners.InlineCompletionDocumentListener@5e20771d, com.intellij.codeInsight.daemon.impl.ExternalToolPass$2@5aaa0af5]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:995)
	at dev.nx.console.nxls.managers.DocumentManager.removeDocumentListener(DocumentManager.kt:145)
	at dev.nx.console.nxls.managers.DocumentManager.documentClosed(DocumentManager.kt:130)
	at dev.nx.console.nxls.NxlsWrapper.disconnect(NxlsWrapper.kt:180)
	at dev.nx.console.services.NxlsService.removeDocument(NxlsService.kt:150)
	at dev.nx.console.listeners.NxEditorListener.editorReleased(NxEditorListener.kt:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$5(EditorFactoryImpl.java:243)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:50)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:243)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.disposeEditor(TextEditorComponent.kt:139)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.kt:128)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.kt:80)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:55)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1777)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl(EditorWindow.kt:571)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile$intellij_platform_ide_impl$default(EditorWindow.kt:559)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile$intellij_platform_ide_impl(FileEditorManagerImpl.kt:696)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.kt:717)
	at com.intellij.openapi.fileEditor.impl.tabActions.CloseTab.actionPerformed(CloseTab.kt:101)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:344)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:318)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:381)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:318)
	at com.intellij.ui.tabs.impl.ActionButton.actionPerformed(ActionButton.java:138)
	at com.intellij.ui.InplaceButton.doClick(InplaceButton.java:93)
	at com.intellij.ui.InplaceButton$1.execute(InplaceButton.java:54)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:213)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:195)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

</details>

**Comment by MaxKless** [comment]
It's released, please let me know here whether it works.

**Comment by jase88** [comment]
looking good - at least my reproducible case does not occur anymore. Thank you!
