### ISSUE TITLE
Brand new nx workspace doesn't work in WebStorm repeatedly asks to Refresh Nx Workspace

### ISSUE THREAD

**Issue by charlesritchea** [nrwl/nx-console#1953]
## Current Behavior

Nx Console says:

There was a problem analysing the current workspace. This could be due to an invalid configuration file, or node_modules not being installed. If everything looks correct, refresh the workspace

Clicking on Refresh Nx Workspace repeates the error

## Steps to Reproduce

Ran `npx create-nx-workspace@latest wireframe-tool-next --preset=angular-monorep` then opened in WebStorm 2023.3 

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/1656349/4d4431b9-6696-47ca-a9e9-2018aa9b9ffa)

```
2023-12-06 22:04:47,644 [5146396]   INFO - #dev.nx.console.nxls.NxlsProcess - Staring the nxls process in workingDir /home/novaterata/Projects/wireframe-tool-next
2023-12-06 22:04:47,644 [5146396]   INFO - #dev.nx.console.nxls.NxlsProcess - nxls found via /home/novaterata/.local/share/JetBrains/WebStorm2023.3/nx-console/nxls/main.js
2023-12-06 22:04:47,646 [5146398]   INFO - #dev.nx.console.nxls.NxlsProcess - nxls started: Process[pid=1096802, exitValue="not exited"]
2023-12-06 22:04:47,716 [5146468]   INFO - #dev.nx.console.nxls.NxlsWrapper - Stopping nxls
2023-12-06 22:04:47,716 [5146468]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2023-12-06 22:04:47,716 [5146468]   INFO - #dev.nx.console.nxls.NxlsWrapper - java.util.concurrent.CancellationException
2023-12-06 22:04:47,716 [5146468]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2023-12-06 22:04:47,716 [5146468]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2023-12-06 22:06:16,078 [5234830]   INFO - #dev.nx.console.nxls.NxlsProcess - Staring the nxls process in workingDir /home/novaterata/Projects/wireframe-tool-next
2023-12-06 22:06:16,078 [5234830]   INFO - #dev.nx.console.nxls.NxlsProcess - nxls found via /home/novaterata/.local/share/JetBrains/WebStorm2023.3/nx-console/nxls/main.js
2023-12-06 22:06:16,081 [5234833]   INFO - #dev.nx.console.nxls.NxlsProcess - nxls started: Process[pid=1098825, exitValue="not exited"]
2023-12-06 22:06:16,150 [5234902]   INFO - #dev.nx.console.nxls.NxlsWrapper - Stopping nxls
2023-12-06 22:06:16,150 [5234902]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2023-12-06 22:06:16,150 [5234902]   INFO - #dev.nx.console.nxls.NxlsWrapper - java.util.concurrent.CancellationException
2023-12-06 22:06:16,150 [5234902]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
2023-12-06 22:06:16,150 [5234902]   INFO - #dev.nx.console.nxls.NxlsWrapper - Unable to send messages to the nxls, the process has exited
```

### Environment

Latest Pop_os! amd64

- Nx Console version: 1.15.1
- WebStorm version: 2023.3 (but happenen on 2023.2 as well)

**Comment by MaxKless** [comment]
Thanks for the report! I will look into it 

Could you provide some logs? 
Go to `Help` > `Diagnostic Tools` > `Debug Log Settings.`.. and then insert `#dev.nx.console:trace`. Then paste the `idea.log` or sections of it when the error happens.

Also the `daemon.log` & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`

**Comment by charlesritchea** [comment]
[webstorm-logs-20231207-085829771154946698220623.zip](https://github.com/nrwl/nx-console/files/13600939/webstorm-logs-20231207-085829771154946698220623.zip)

**Comment by charlesritchea** [comment]
That's with latest, I'll try canary

**Comment by charlesritchea** [comment]
[webstorm-logs-20231207-0900307200444148208862825.zip](https://github.com/nrwl/nx-console/files/13600958/webstorm-logs-20231207-0900307200444148208862825.zip)

**Comment by charlesritchea** [comment]
Just got this using nx 15 now (started reproducing there too)
```
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$7$lambda$6(NxlsWrapper.kt:95)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at jdk.proxy6/jdk.proxy6.$Proxy168.initialize(Unknown Source)
	at dev.nx.console.nxls.NxlsWrapper.start(NxlsWrapper.kt:120)
	at dev.nx.console.services.NxlsService.start(NxlsService.kt:40)
	at dev.nx.console.ProjectPostStartup.execute(ProjectPostStartup.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:482)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 14 more
```

**Comment by MaxKless** [comment]
Hey! Is this still happening on the latest version @charlesritchea? We've done a lot of refactorings of the nxls process (which uses the stream that's closed in your example) recently.

**Comment by charlesritchea** [comment]
Not happening for me
