### ISSUE TITLE
Nx Console encountered an issue when activating

### ISSUE THREAD

**Issue by cutterbl** [nrwl/nx-console#1995]
## Current Behavior

After the most recent update to my Nx Console extension is (Mac) VS Code I am receiving the following error every time I open a VS Code instance:

```
Telemetry: production
Nx Console encountered an error when activating
TypeError: Cannot read properties of undefined (reading 'sendRequest')
    at sendRequest (/Users/SomeUser/libs/vscode/lsp-client/src/lib/configure-lsp-client.ts:92:18)
    at getNxWorkspacePath (/Users/SomeUser/libs/vscode/nx-workspace/src/lib/get-nx-workspace-path.ts:5:10)
    at initVscodeProjectDetails (/Users/SomeUser/libs/vscode/project-details/src/lib/init-vscode-project-details.ts:23:3)
    at fkn (/Users/SomeUser/apps/vscode/src/main.ts:133:5)
    at u.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
    at u.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
    at u.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)
```
I'm guessing the extension is trying to make some remote call and my company's firewall is blocking the request. I can request a whitelist (if that is the issue), if I knew where it was calling, and could explain the use case to my security team.

I do use `nvm`, and my default Node version is 16.16.0, if that makes a difference.

## Expected Behavior

Expect VS Code to open without errors from Nx Console initialization. This worked fine until v18.14.0

### Environment

- Mac: 14.2.1
- VS Code: 1.85.2
- Nx Console: 18.14.0

**Comment by MaxKless** [comment]
Hey thanks for the report, I'll fix it ASAP.
