### ISSUE TITLE
properties of undefined - 'sendRequest'

### ISSUE THREAD

**Issue by godzzo** [nrwl/nx-console#1996]
## Current Behavior
Showing error message when start VSCode.

## Expected Behavior

Not showing error message.

## Steps to Reproduce

Open VSCode (without open folder / workspace).

### Failure Logs / Images / Videos

In output:

```log
Telemetry: production
Nx Console encountered an error when activating
TypeError: Cannot read properties of undefined (reading 'sendRequest')
    at sendRequest (/home/user/libs/vscode/lsp-client/src/lib/configure-lsp-client.ts:92:18)
    at getNxWorkspacePath (/home/user/libs/vscode/nx-workspace/src/lib/get-nx-workspace-path.ts:5:10)
    at initVscodeProjectDetails (/home/user/libs/vscode/project-details/src/lib/init-vscode-project-details.ts:23:3)
    at fkn (/home/user/apps/vscode/src/main.ts:133:5)
    at u.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
    at u.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
    at u.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)
```

![kép](https://github.com/nrwl/nx-console/assets/912200/766f3781-afb1-4478-9779-f8571d4cbe48)

### Environment

- Nx Console version: 18.14.0
- VSCode version: 1.85.2
- Ubuntu 22.04

**Comment by godzzo** [comment]
Duplicate of this: #1995 (_almost same time, din not see when I filled the report..._)

**Comment by MaxKless** [comment]
Hey thanks for the report, I'll fix it ASAP.
