### ISSUE TITLE
Nx Language Server Quits on Startup Without core-js module installed

### ISSUE THREAD

**Issue by Drew-Daniels** [nrwl/nx-console#2019]
## Current Behavior

I am using `neovim` as my editor, [mason](https://github.com/williamboman/mason.nvim) as my package manager, and [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#nxls) to hook my LSP servers into `neovim`.

After installing `nxls` with `mason`, and configuring `neovim` to use `nxls` as a language server for `.json` files, when I open an `nx.json` file (or any `.json` file now), I see an error message stating that `nxls` failed to start.

When I look at the logs, I see that the reason it failed is because it cannot find the `core-js` module. 

```
[ERROR][2024-02-06 20:47:20] .../vim/lsp/rpc.lua:31	"rpc"	"/Users/drew/.local/share/nvim/mason/bin/nxls"	"stderr"	"node:internal/modules/cjs/loader:1147\n  throw err;\n  ^\n\nError: Cannot find module 'core-js/modules/es.regexp.to-string.js'\nRequire stack:\n- /Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js\n- /Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/bin/nxls\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)\n    at Module._load (node:internal/modules/cjs/loader:985:27)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at /Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:866\n    at /Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:39087\n    at Object.<anonymous> (/Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:39193)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js',\n    '/Users/drew/.local/share/nvim/mason/packages/nxls/node_modules/nxls/bin/nxls'\n  ]\n}\n\nNode.js v20.11.0\n"
```

I do not see this listed anywhere in the [dependencies](https://github.com/nrwl/nx-console/blob/master/apps/nxls/package.json) section of `nxls`, and can see that the only packages that explicitly require it are `@storybook/addon-knobs` and `@wdio/devtools-service`.

![image](https://github.com/nrwl/nx-console/assets/62859552/d60c6b0c-7fd8-42ea-aaf4-e96584d7df97)

However, when I look at `nxls/node_modules/.bin/nxls`, which is the executable I have `neovim` pointed to as the language server for `nx` files, I can see that it requires `nxls/main.js`, which in turn requires `core-js/modules/es.regexp.to-string.js`:

![image](https://github.com/nrwl/nx-console/assets/62859552/69d088e7-fbf0-49e1-a460-af1109e9a3f7)

## Expected Behavior

I would expect that by downloading `nxls`, all of it's required dependencies are installed.

## Steps to Reproduce

- Configure `neovim` as I have [here](https://github.com/Drew-Daniels/dotfiles/tree/master/nvim)
- Run `:MasonInstallAll` in `neovim` to install all packages (includes`nxls`)
- Open a `.json` file with `neovim`:
```bash
$ nvim test.json
```
- See that you get an error message stating "Client nxls quit with exit code 1 and signal 0..."

![image](https://github.com/nrwl/nx-console/assets/62859552/512cf42b-a87b-4bb6-ac1e-f815a09c29c7)

### Environment
OS: MacOS Sonoma 14.2.1 (23C71)
Neovim: 
```bash
NVIM v0.10.0-dev-2294+gc0b99bb1d-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

- Nx Console version: N/A
- VSCode version: N/A

**Comment by Cammisuli** [comment]
yea, you're right. Nxls doesnt have core-js as a dependency. I think we might have to release a newer version of nxls to npm, we havent done that in a while. Sorry about that!

**Comment by Drew-Daniels** [comment]
No worries! Thanks for taking a look

**Comment by chaozwn** [comment]
> yea, you're right. Nxls doesnt have core-js as a dependency. I think we might have to release a newer version of nxls to npm, we havent done that in a while. Sorry about that!

I am also getting the same error now, is nxls updated recently.

```
"rpc" "/Users/jayce.zhao/.local/share/nvim/mason/bin/nxls" "stderr" "node:internal/modules/cjs/loader:1228\n throw err;\n ^\n\nError: **Cannot find module 'core-js/modules/es.regexp.to-string.js'**\nRequire stack:\n- /Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js\n- /Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/bin/nxls\n at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n at Module._load (node:internal/modules/cjs/loader:1051:27)\n at Module.require (node:internal/modules/cjs/loader:1311:19)\n at require (node:internal/modules/helpers:179:18)\n at /Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:866\n at /Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:39087\n at Object.<anonymous> (/Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js:1:39193)\n at Module._compile (node:internal/modules/cjs/loader:1469:14)\n at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)\n at Module.load (node:internal/modules/cjs/loader:1288:32) {\n code: 'MODULE_NOT_FOUND',\n requireStack: [\n '/Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/main.js',\n '/Users/jayce.zhao/.local/share/nvim/mason/packages/nxls/node_modules/nxls/bin/nxls'\n ]\n}\n\nNode.js v20.18.2\n"
```

**Comment by ShuviSchwarze** [comment]
Is there any plan to update the npm package?

**Comment by MaxKless** [comment]
Yes there is, just haven't gotten around to it yet. I will do it soon. If you need it right now, you can always build from source using this repo :)

**Comment by JosefBud** [comment]
@MaxKless Any chance you'd have time to update the npm package? I'm trying to use `nxls` in neovim but can't get past this issue :)

**Comment by MaxKless** [comment]
yeah I'll get a new version out, the groundwork is already laid out

**Comment by MaxKless** [comment]
We've started releasing version of the nxls regularly again btw, just got one out today :)
