### ISSUE TITLE
nx console crashes in vscode on mac on reconfiguration while reading the displayName of angular jest.config.ts

### ISSUE THREAD

**Issue by sn0wcat** [nrwl/nx-console#2047]
## Current Behavior

The nx console crashes on every reconfiguration while trying to load the angular jest settings.

## Expected Behavior

The console loads the project tree.

## Steps to Reproduce

Trigger reloading of the nx angular console. 
![image](https://github.com/nrwl/nx-console/assets/1426617/ad1cb2a1-c5ea-43f3-8cd1-47c149ee1c00)

After the console reloads the project tree, it crashes while reading the jest.config.ts in the root of the angular folder. It crashes while trying to parse the displayName from the settings. This doesn't happen on initial loading (closing / reopening vscode) just on reconfiguration.

```logs
[Nxls] - 2024-03-11T08:49:34.042Z - createProjectGraphAndSourceMapsAsync

Unable to create nodes for dashboard/jest.config.ts using plugin @nx/jest/plugin. 

	 Inner Error: ● Validation Error:

  Option "displayName" must be of type:
    array
  but instead received:
    object

  Example:
  {
    "displayName": [
      "test-config",
      {
        "color": "blue",
        "name": "test-config"
      }
    ]
  }

  Configuration Documentation:
  https://jestjs.io/docs/configuration

[Nxls] - 2024-03-11T08:49:34.999Z - Unable to get project graph

[Nxls] - 2024-03-11T08:49:34.999Z - Error: Unable to create nodes for dashboard/jest.config.ts using plugin @nx/jest/plugin. 

	 Inner Error: ● Validation Error:

  Option "displayName" must be of type:
    array
  but instead received:
    object

  Example:
  {
    "displayName": [
      "test-config",
      {
        "color": "blue",
        "name": "test-config"
      }
    ]
  }

  Configuration Documentation:
  https://jestjs.io/docs/configuration

    at /Users/sn0wcat/developer-dashboard/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:156:35
    at async Promise.all (index 2)
    at async Promise.all (index 2)
    at async createProjectConfigurations (/Users/sn0wcat/developer-dashboard/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:62)
    at async buildProjectGraphAndSourceMapsWithoutDaemon (/Users/sn0wcat/developer-dashboard/node_modules/nx/src/project-graph/project-graph.js:71:69)
    at async Object.createProjectGraphAndSourceMapsAsync (/Users/sn0wcat/developer-dashboard/node_modules/nx/src/project-graph/project-graph.js:136:25)
    at async rKt (/Users/sn0wcat/.vscode/extensions/nrwl.angular-console-18.17.0/nxls/main.js:863:16583)
    at async K6n (/Users/sn0wcat/.vscode/extensions/nrwl.angular-console-18.17.0/nxls/main.js:863:18885)

[Nxls] - 2024-03-11T08:49:34.999Z - Resetting daemon client
[Nxls] - 2024-03-11T08:49:34.999Z - Retrieved workspace configuration in: 958.6977089643478 ms
```

### Failure Logs / Images / Videos
[12-Nx Console Client.log](https://github.com/nrwl/nx-console/files/14556274/12-Nx.Console.Client.log)

### Environment

- Nx Console version:
- VSCode version:
```text
code --version
1.87.1
1e790d77f81672c49be070e04474901747115651
arm64
```

```
❯ yarn nx report
yarn run v1.22.19
$ /Users/sn0wcat/developer-dashboard/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.19.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/nest           : 18.0.4
   @nx/node           : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3

✨  Done in 2.69s.
```

deleting displayName from the settings seems to remediate the issue for now.

**Comment by MaxKless** [comment]
Thanks for the report. This is actually an issue with nx itself, nx console just inherits it. The team is aware of it and working on a fix as we speak. I'll close this issue in the meantime :)

**Comment by sn0wcat** [comment]
@maxkless is there an issue in nx repository i should be watching? I couldn't find anything related to this crash, and the behavior is the same with 18.0.8 as well.

**Comment by MaxKless** [comment]
I think this PR should have the changes you're looking for: https://github.com/nrwl/nx/pull/22224
