### ISSUE TITLE
[Webstorm]: java.nio.file.InvalidPathException: Illegal char <:> at index 32: /HTML Fragment

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#2086]
## Current Behavior

The plugin breaks `Edit HTML Fragment` functionality and throws an exception.

![image](https://github.com/nrwl/nx-console/assets/1770529/53d46d1c-3098-4972-b86f-26b8f1834e84)
![image](https://github.com/nrwl/nx-console/assets/1770529/fc4cf369-9549-44e7-a921-b5602b84effc)

## Expected Behavior

`Edit HTML Fragment` panel must be shown

![image](https://github.com/nrwl/nx-console/assets/1770529/858e037c-b9a6-4339-a3e9-ec3d27564007)

## Steps to Reproduce

1. Generate nx repo
```
npx create-nx-workspace@latest nx1823 --preset=angular-monorepo --appName=my-app --style=css --nx-cloud=skip --unitTestRunner=none --e2eTestRunner=none --bundler=esbuild --ssr=false
```
2. add the following content into some ts file
```ts
const template = `<h1></h1>`
```
3. using the context menu call `Edit HTML Fragment`

### Failure Logs / Images / Videos

```
java.nio.file.InvalidPathException: Illegal char <:> at index 32: /HTML Fragment (app.component.ts:17).html
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at dev.nx.console.project_details.ProjectConfigFilesService.isProjectDetailsFile(ProjectConfigFilesService.kt:38)
	at dev.nx.console.project_details.ProjectDetailsFileEditorProvider.accept(ProjectDetailsFileEditorProvider.kt:17)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.checkProvider(FileEditorProviderManagerImpl.kt:214)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImplKt.access$checkProvider(FileEditorProviderManagerImpl.kt:1)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviderList$lambda$2(FileEditorProviderManagerImpl.kt:66)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:289)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviderList(FileEditorProviderManagerImpl.kt:64)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.canOpenFile(FileEditorManagerEx.kt:113)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1006)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.split(EditorWindow.kt:413)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.split$default(EditorWindow.kt:363)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.split(EditorWindow.kt)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler.navigate(QuickEditHandler.java:212)
	at com.intellij.codeInsight.intention.impl.QuickEditAction.invokeImpl(QuickEditAction.java:101)
	at com.intellij.codeInsight.intention.impl.QuickEditAction.invoke(QuickEditAction.java:88)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:80)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:251)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:398)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$9(ShowIntentionActionsHandler.java:313)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:225)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:312)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:143)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:135)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1766)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$4(FocusManagerImpl.java:174)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:226)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:192)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:170)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:164)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1764)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:178)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:404)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:205)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:193)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:286)
	at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:528)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:552)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:515)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:446)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:287)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:415)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:387)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:123)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:164)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:96)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:566)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Environment

- Nx Console version: 1.20.0
- WebStorm version: 2024.1

**Comment by MaxKless** [comment]
Thanks for the report @Den-dp! This is already fixed with https://github.com/nrwl/nx-console/pull/2076 and will be released soon :)
