### ISSUE TITLE
Cannot open generator UI in VSCode

### ISSUE THREAD

**Issue by guysenpai** [nrwl/nx-console#2148]
## Current Behavior

When I click on `generate` in vscode sidebar the generator ui does not open

## Expected Behavior

The generator open

## Steps to Reproduce

- clone this repo https://github.com/guysenpai/nx-console-bug.git
- open in vscode
- install dependencies
- try to generate using nx console

### Failure Logs / Images / Videos

![Screenshot from 2024-05-25 10-22-13](https://github.com/nrwl/nx-console/assets/6205146/6d4ca468-c75c-413f-b1df-58b949817eb6)

### Environment

- Nx Console version: 18.21.3
- VSCode version: 1.89.1

**Comment by orlovvvv** [comment]
Generators seem to work for clean project (no framework preset + integrated monorepo) 

```json
{
  "devDependencies": {
    "@nx/js": "19.1.0",
    "@nx/workspace": "19.1.0",
    "nx": "19.1.0"
  }
}
```
```json
{
  "devDependencies": {
    "@nx/angular": "19.1.0",
    "@nx/js": "19.1.0",
    "@nx/workspace": "19.1.0",
    "nx": "19.1.0"
  }
}
```
untill I installed @nx/angular. Then the issue with generating by UI begins to occur and the same mesasge in NX Language Server output can be seen.

**Comment by jvoigt** [comment]
I get the same error in Intellji Ultimate

IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024
Nx Console: 1.24.0 (2024-05-10
node npmv20.13.1
 npm 10.5.2

```
Unhandled exception in [ComponentManager(ProjectImpl@1188904724), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@72e34a57, Dispatchers.Default]

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$9$lambda$8(NxlsWrapper.kt:109)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1188904724), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelled}@72e34a57, Dispatchers.Default]
```

I hope this helps. Thanks for all the great work!
