### ISSUE TITLE
"We couldn't find any projects in this workspace" 

### ISSUE THREAD

**Issue by BoilerTom90** [nrwl/nx-console#2153]
## Current Behavior

I have an nx repo, and nx console was working great for a while.  I created a few lib projects within the repo, and added some angular components to the lib. All of a sudden I noticed the "nx generate" command wouldn't work. The many other commands that were listed seemed to be working. 

I restarted vscode, and now the extension is saying "We couldn't find any projects in this workspace."  Also, in the list of commands, it's only showing "generate", "run" and "Change workspace".  

## Expected Behavior

I'm expecting the nx console to recognize the workspace as an nx workspace, to find all the projects, and to list all of the commands.

## Steps to Reproduce

I'm not sure what I did to get nx console into this state.  It's interesting that I have other nx projects that do not have this problem; meaning nx console is working fine. 

### Failure Logs / Images / Videos

When I click "Refresh Workspace," I see the following messages in the nx console output log:

```bash
[Nxls] - 2024-06-03T16:18:44.687Z - Retrieving workspace configuration

[Nxls] - 2024-06-03T16:18:44.689Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/utils/output.js

[Nxls] - 2024-06-03T16:18:44.690Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-06-03T16:18:44.690Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-06-03T16:18:44.690Z - Using local Nx package at d:/projects/nx-xcreg/xcreg3/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-06-03T16:18:44.697Z - createProjectGraphAsync

[Nxls] - 2024-06-03T16:18:44.727Z - createProjectGraphAsync successful

process.exit called with code 1
[Nxls] - 2024-06-03T16:18:44.730Z - Unable to get nx workspace configuration: Error: Daemon process terminated and closed the connection

Messages from the log:
[NX Daemon Server] - 2024-06-03T16:18:35.693Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-06-03T16:18:35.696Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-03T16:18:35.696Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-06-03T16:18:35.696Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-03T16:18:35.702Z - [REQUEST]: Responding to the client. handleRequestFileData
[NX Daemon Server] - 2024-06-03T16:18:35.702Z - Done responding to the client handleRequestFileData
[NX Daemon Server] - 2024-06-03T16:18:35.702Z - Handled REQUEST_FILE_DATA. Handling time: 1. Response time: 0.
[NX Daemon Server] - 2024-06-03T16:18:44.697Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-06-03T16:18:44.697Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-03T16:18:44.698Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-06-03T16:18:44.700Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-06-03T16:18:44.722Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-06-03T16:18:44.723Z - Time taken for 'total for creating and serializing project graph' 22.38090000115335ms
[NX Daemon Server] - 2024-06-03T16:18:44.723Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-06-03T16:18:44.723Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 22. Response time: 1.
[NX Daemon Server] - 2024-06-03T16:18:44.727Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-03T16:18:44.728Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-06-03T16:18:44.729Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-03T16:18:44.729Z - Established a connection. Number of open connections: 3



More information: d:\projects\nx-xcreg\xcreg3\.nx\cache\d\daemon.log

[Error - 11:18:44 AM] Unhandled exception: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at resolve (node:path:161:9)
    at h (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:10317)
    at kGe (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:10593)
    at oJt (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:10200)
    at async Promise.all (index 17)
    at async hye (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:9867)
    at async dJt (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:15509)
    at async fzt (c:\Users\hoffmat\.vscode\extensions\nrwl.angular-console-18.12.0\nxls\main.js:828:34029)

```

### Environment

Windows
nx console: 18.12.0
node: 18.19.1
vscode: 1.82.2

**Comment by MaxKless** [comment]
Hey @BoilerTom90! Thanks a lot for the report. I appreciate you taking the time. 
Is there a specific reason you're on vscode `1.82.2`?
The latest Nx Console versions require `1.89` or up, which is probably why you're on nx console`18.12.0` while the latest version is `18.21.4`.
I'll close this for now but if you can reproduce on the latest vscode & nx console versions, I'll gladly reopen it and have a look.

**Comment by BoilerTom90** [comment]
Thank you.  I’ll upgrade and see if the problem goes away.

Regards
