### ISSUE TITLE
Generate UI dropdown fails to render

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx-console#2167]
## Current Behavior
generate dropdown fails to render

the generate UI portion fails to show up at all

plugin generates nothing

cannot generate anything dropdown with metadata content fails to render

## Expected Behavior

its suppose to work as designed

## Steps to Reproduce

install latest webstorm trial
install NxConsole plugin (tried every which way repeatedly)

same behavior persists

### Failure Logs / Images / Videos

none

### Environment

% nx report
```
Node   : 22.2.0
OS     : darwin-x64
yarn   : 1.22.22

nx (global)        : 19.2.3
nx                 : 19.2.3
@nx/js             : 19.2.3
@nx/jest           : 19.2.3
@nx/linter         : 19.2.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.2.3
@nx/angular        : 19.2.3
@nx/cypress        : 19.2.3
@nx/devkit         : 19.2.3
@nrwl/devkit       : 13.10.6
@nx/eslint-plugin  : 19.2.3
@nx/express        : 19.2.3
@nx/nest           : 19.2.3
@nx/node           : 19.2.3
@nx/storybook      : 19.2.3
@nrwl/tao          : 19.2.3
@nx/web            : 19.2.3
@nx/webpack        : 19.2.3
typescript         : 5.4.5
---------------------------------------
Community plugins:
@compodoc/compodoc                    : 1.1.25
@fortawesome/angular-fontawesome      : 0.11.1
@ionic/angular                        : 6.7.5
@jsverse/transloco                    : 7.4.2
@ngrx/component                       : 17.0.1
@ngrx/component-store                 : 17.0.1
@ngrx/effects                         : 17.0.1
@ngrx/entity                          : 17.0.1
@ngrx/router-store                    : 17.0.1
@ngrx/schematics                      : 17.0.1
@ngrx/store                           : 17.0.1
@ngrx/store-devtools                  : 17.0.1
@nxtend/capacitor                     : 13.0.0
@nxtend/ionic-angular                 : 13.1.0
@storybook/angular                    : 7.6.6
angular-builder-custom-terser-options : 1.0.1
apollo-angular                        : 4.2.1
---------------------------------------

**Comment by nhhockeyplayer** [comment]
field developers and consultants would appreciate the NX team yank this away from the originators who have obviously abandoned their interest and responsibility of publishing something into the public domain responsibly with the @NRWL brand likely for their own personal notoriety.. and adopt developing this plugin so it can be a reliable mainstay for the nrwl nx product

this is a stain on the victor savkin masterpiece

**Comment by MaxKless** [comment]
Hey.
I edited your issue to include only the relevant parts.
I'm sorry you're running into issues with Nx Console. I appreciate you reporting the issue so we can make it better. However, the way you're doing it is not okay. Being agressive and insulting isn't going to get your issue resolved any faster. 

If you read through the `nx report` you've pasted and the warning it included, you will see that your `devkit` version is heavily mismatched with the rest of your nx versions. As you might be able to imagine, Nx Console uses the devkit heavily. 
Please try and fix this warning and try if the issue persists again. Ideally before creating an issue like this. 

If the issue still persists and you want anyone to be able to help you, please provide some logs. 
Go to `Help` > `Diagnostic Tools` > `Debug Log Settings.`.. and then insert `#dev.nx.console:trace`. Then paste the `idea.log` or sections of it when the error happens.

Then paste them here so I can try to figure out what's going on.

The Nx Console plugin is developed by Nx itself and so noone will be yanking it away. Please be more constructive in the future, even if you're frustrated over a bug.

**Comment by nhhockeyplayer** [comment]
thanks friend

```
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@13.10.6

To fix this, run `nx migrate nx@19.2.3`

```
my package.json has no `@nrwl/devkit` in it
it has     `"@nx/devkit": "19.2.3",`

and upon acting on the warning with `nx migrate nx@19.2.3`
nothing changes and remains the same
so the warning suggestion is a guess
and nx appears confused
to what extent does this contribute to the issue?

the plugin use to work fine

**Comment by MaxKless** [comment]
>If the issue still persists and you want anyone to be able to help you, please provide some logs.
Go to Help > Diagnostic Tools > Debug Log Settings... and then insert #dev.nx.console:trace. Then paste the idea.log or sections of it when the error happens.

**Comment by nhhockeyplayer** [comment]
here is the log as requested

% tail -f  ~/Library/Logs/JetBrains/WebStorm2024.1/idea.log | tee idea.output.log
```
2024-06-14 14:58:34,480 [ 127914]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.usages.UsageNodePresentation <clinit> requests com.intellij.usageView.UsageTreeColorsScheme instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
2024-06-14 14:58:34,647 [ 128081]   INFO - #c.i.p.c.CustomCodeStyleSettings - Loaded com.intellij.psi.formatter.xml.HtmlCodeStyleSettings
2024-06-14 14:58:34,647 [ 128081]   INFO - #c.i.p.c.CustomCodeStyleSettings - Loaded com.intellij.lang.typescript.formatter.TypeScriptCodeStyleSettings
2024-06-14 14:58:34,647 [ 128081]   INFO - #c.i.p.c.CommonCodeStyleSettings - Loaded JSON common code style settings
2024-06-14 14:58:34,647 [ 128081]   INFO - #c.i.p.c.CommonCodeStyleSettings - Loaded TypeScript common code style settings
2024-06-14 14:58:38,194 [ 131628]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.ui.jcef.JBCefApp$Holder <clinit> requests com.intellij.ui.jcef.JBCefAppCache instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
2024-06-14 14:58:38,196 [ 131630]   INFO - #c.i.u.j.JBCefApp - JCEF-sandbox is enabled
2024-06-14 14:58:38,712 [ 132146]   INFO - #c.i.u.j.JBCefApp - jcef version: 122.1.9.763.fea36f6f27abf2ae4534240ef35488664890a2a5 | cmd args: [--disable-in-process-stack-traces, --use-mock-keychain, --disable-features=SpareRendererForSitePerProcess, --no-proxy-server, --disable-gpu-process-crash-limit, --autoplay-policy=no-user-gesture-required]
2024-06-14 14:58:46,510 [ 139944]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-14 14:58:46,510 [ 139944]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-14 14:59:27,544 [ 180978]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [meanstacknh]
2024-06-14 14:59:27,578 [ 181012]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@2356c44b (reason: Push on VFS changes)
2024-06-14 14:59:27,597 [ 181031]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@2356c44b (reason: Push on VFS changes)
2024-06-14 14:59:27,629 [ 181063]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [meanstacknh]
2024-06-14 14:59:32,159 [ 185593]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-14 14:59:32,160 [ 185594]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-14 14:59:47,096 [ 200530]   WARN - #c.i.u.x.Binding - No accessors for git4idea.search.FilterState. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-06-14 14:59:50,908 [ 204342]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.JadeBundle
2024-06-14 14:59:50,910 [ 204344]   INFO - #c.i.i.p.PluginManager - Cannot find plugin com.jetbrains.plugins.jade resource-bundle: messages.JadeBundle
2024-06-14 14:59:50,911 [ 204345]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.HgBundle
2024-06-14 14:59:50,913 [ 204347]   INFO - #c.i.i.p.PluginManager - Cannot find plugin hg4idea resource-bundle: messages.HgBundle
2024-06-14 14:59:50,913 [ 204347]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.SvnBundle
2024-06-14 14:59:50,914 [ 204348]   INFO - #c.i.i.p.PluginManager - Cannot find plugin Subversion resource-bundle: messages.SvnBundle
2024-06-14 14:59:50,915 [ 204349]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.VueBundle
2024-06-14 14:59:50,916 [ 204350]   INFO - #c.i.i.p.PluginManager - Cannot find plugin org.jetbrains.plugins.vue resource-bundle: messages.VueBundle
2024-06-14 14:59:50,918 [ 204352]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.TsLintBundle
2024-06-14 14:59:50,919 [ 204353]   INFO - #c.i.i.p.PluginManager - Cannot find plugin tslint resource-bundle: messages.TsLintBundle
2024-06-14 14:59:51,211 [ 204645]   INFO - #c.i.n.NotificationGroup - Notification group Barrels plugin is already registered
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:64)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:20)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:51)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:46)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt)
	at com.starzec.piotr.CreateBarrelAction.<init>(CreateBarrelAction.java:41)
	at com.starzec.piotr.CreateJavaScriptBarrelAction.<init>(CreateJavaScriptBarrelAction.java:13)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:908)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:917)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:902)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1451)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1685)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.getAction(ActionManagerImpl.kt:2167)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$getAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:420)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2$1.invokeSuspend(ActionAsyncProvider.kt:336)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-06-14 14:59:51,263 [ 204697]   WARN - #c.i.o.a.ActionStub - ActionGroup should be registered using <group> tag: id="GitBranchesTreePopupFilterSeparatorWithText" class="git4idea.ui.branch.popup.GitBranchesTreePopupFilterSeparatorWithText"
2024-06-14 14:59:51,590 [ 205024]   INFO - #c.i.n.NotificationGroup - Notification group Barrels plugin is already registered
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:64)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:20)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:51)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:46)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt)
	at com.starzec.piotr.CreateBarrelAction.<init>(CreateBarrelAction.java:41)
	at com.starzec.piotr.CreateScssBarrelAction.<init>(CreateScssBarrelAction.java:13)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:908)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:917)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:902)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1451)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1685)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.getAction(ActionManagerImpl.kt:2167)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$getAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:420)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2$1.invokeSuspend(ActionAsyncProvider.kt:336)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-06-14 14:59:52,617 [ 206051]   INFO - #dev.nx.console.telemetry.TelemetryService - REQUEST: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> Accept: */*
-> Accept-Charset: UTF-8
CONTENT HEADERS
-> Content-Length: 461
-> Content-Type: text/plain; charset=UTF-8
BODY Content-Type: text/plain; charset=UTF-8
BODY START
{"events":[{"name":"action_triggered","params":{"engagement_time_msec":"1","session_id":"c1d0c5ba-b7ab-43ff-99ef-8b1c63f9c1e9","debug_mode":false,"action_type":"Nx Generate UI"}}],"client_id":"633d8413-9708-4770-bf21-ed015fde222b","user_id":"633d8413-9708-4770-bf21-ed015fde222b","timestamp_micros":1718391592615000,"non_personalized_ads":true,"user_properties":{"editor":{"value":"WebStorm 2024.1.4"},"os":{"value":"Mac OS X"},"appversion":{"value":"1.25.0"}}}
BODY END
2024-06-14 14:59:52,620 [ 206054]  FINER - #dev.nx.console.nxls.NxlsWrapper - Sending request to nxls: nx/generators (NxGeneratorsRequest(options=NxGeneratorsRequestOptions(includeHidden=false, includeNgAdd=false)))
2024-06-14 14:59:52,806 [ 206240]  FINER - #dev.nx.console.nxls.NxlsWrapper - Error from nxls: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-06-14 14:59:52,811 [ 206245] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in [ComponentManager(ProjectImpl@2077789844), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@774bf0b1, Dispatchers.Default]
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$9$lambda$8(NxlsWrapper.kt:109)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-14 14:59:52,816 [ 206250] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - WebStorm 2024.1.4  Build #WS-241.17890.13
2024-06-14 14:59:52,816 [ 206250] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-06-14 14:59:52,817 [ 206251] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - OS: Mac OS X
2024-06-14 14:59:52,817 [ 206251] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Plugin to blame: Nx Console version: 1.25.0
2024-06-14 14:59:52,817 [ 206251] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Last Action: dev.nx.console.generate.actions.NxGenerateUiAction
2024-06-14 14:59:52,822 [ 206256]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-4" org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: The "paths[2]" argument must be of type string. Received undefined
2024-06-14 14:59:52,822 [ 206256]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
2024-06-14 14:59:52,822 [ 206256]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
2024-06-14 14:59:52,822 [ 206256]   INFO - STDERR - 	at dev.nx.console.nxls.NxlsWrapper.start$lambda$9$lambda$8(NxlsWrapper.kt:109)
2024-06-14 14:59:52,822 [ 206256]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-14 14:59:52,823 [ 206257]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@2077789844), CoroutineName(dev.nx.console.generate.NxGenerateService), StandaloneCoroutine{Cancelling}@774bf0b1, Dispatchers.Default]
2024-06-14 14:59:52,849 [ 206283]   INFO - #dev.nx.console.telemetry.TelemetryService - RESPONSE: 204 No Content
METHOD: HttpMethod(value=POST)
FROM: https://www.google-analytics.com/mp/collect?api_secret=3J_QsvygSLKfjxMXFSG03Q&measurement_id=G-TNJ97NGX40
COMMON HEADERS
-> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
-> Cache-Control: no-cache, no-store, must-revalidate
-> Content-Length: 0
-> Content-Type: text/plain
-> Cross-Origin-Resource-Policy: cross-origin
-> Date: Fri, 14 Jun 2024 18:59:52 GMT
-> Expires: Fri, 01 Jan 1990 00:00:00 GMT
-> Last-Modified: Sun, 17 May 1998 03:00:00 GMT
-> Pragma: no-cache
-> Server: Golfe2
BODY Content-Type: text/plain
BODY START

BODY END
2024-06-14 15:00:04,531 [ 217965]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-14 15:00:04,531 [ 217965]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files

```

**Comment by nhhockeyplayer** [comment]
well I am experiencing alot of incoherency with the scaffolding
generate a new project

and under node_modules Im seeing two folders
@nrwl
@nx

and both appear to have identical folders maybe overlap maybe replication maybe

its looking like the transition from scope was not nailed down clean

and Im encountering many faults in just operating the scaffolding of my pre-existing project after migrate and including operating new projects after scaffolding

now I do see new things like playwright and esbuild...
and legacy nx things like jest, webpack, and original things from version 11-15 of nx

the scaffolding comes apart when trying to use the new things

its a little more predictable if I stay with webpack cypress and jest as original

and I feel these breaches (and Im seeing alot between migration, before after in between) that affect the runnability of NxConsole

so having had no luck getting NxConsole to function I just created a new workspace against cypress/jest and original qualified parameters for scaffold and now NxConsole is coming up now

strange

but not encouraging

**Comment by nhhockeyplayer** [comment]
subsequently
webstorm hangs
and needs to be force-quit

im posting the logs for this now

i previously attempted to go thru creating a simple lib UTIL and then removed it
after which everything hung
and NxConsole refuses to launch again... the generate UI

**Comment by nhhockeyplayer** [comment]
so here is the NxConsole after I relaunch everything after force-quit
and new project opened goodgiver
![Screen Shot 2024-06-15 at 11 19 32 PM](https://github.com/nrwl/nx-console/assets/6886551/ae1c84ec-6b85-471b-9f3a-116b8f797686)

**Comment by MaxKless** [comment]
Hey thanks for the logs. Now there is actually relevant information to work with. 

This error should be fixed on the latest version...
This bug was report here https://github.com/nrwl/nx-console/issues/2148 and fixed with this PR 3 weeks ago: https://github.com/nrwl/nx-console/pull/2150

Can you double check your WebStorm & Nx Console versions and let me know what they are?

**Comment by nhhockeyplayer** [comment]
thank you friend
![Screen Shot 2024-07-11 at 5 26 02 PM](https://github.com/user-attachments/assets/30f2e13e-a9eb-4925-ac34-fe5c7dfe30fd)
![Screen Shot 2024-07-11 at 5 26 32 PM](https://github.com/user-attachments/assets/0f88bcc8-b8a2-4256-827f-8a16680ee2e5)

**Comment by nhhockeyplayer** [comment]
appears to be working now appreciate the turnaround
