### ISSUE TITLE
doesn't work with lerna

### ISSUE THREAD

**Issue by DetachHead** [nrwl/nx-console#2275]
## Current Behavior

the description for this project is "Nx Console is the user interface for Nx & Lerna." but it doesn't seem to work on lerna projects.

when attempting to use it on a lerna project, it fails to load anything about my project because there's no `nx.json` file:

## Expected Behavior

it detects `lerna.json` and doesn't complain that there's no `nx.json`

### Failure Logs / Images / Videos

![image](https://github.com/user-attachments/assets/f65c93dc-b3d0-4b9c-99e7-2b75ca828e4f)

```
Error: ENOENT: no such file or directory, open 'c:\Users\user\project\nx.json'
    at readFileSync (node:fs:450:20)
    at t.readFileSync (node:electron/js2c/node_init:2:9900)
    at Object.readJsonFile (c:\Users\user\project\node_modules\nx\src\utils\fileutils.js:25:43)
    at ss (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.28.1\nxls\main.js:92:4374)
    at async lx (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.28.1\nxls\main.js:92:12178)
    at async Vne (c:\Users\user\.vscode\extensions\nrwl.angular-console-18.28.1\nxls\main.js:92:15631)
```

### Environment

- Nx Console version: v18.28.1
- VSCode version: 1.93.1

**Comment by MaxKless** [comment]
Yeah, we support lerna but made a wrong assumption here somewhere. Thanks for catching this!

I'll look into it and fix it, in the meanwhile you can use an earlier version.
