### ISSUE TITLE
NX console vscode extension is unable to reliably find projects in the current workspace

### ISSUE THREAD

**Issue by soosap** [nrwl/nx-console#2302]
## Current Behavior

![Image](https://github.com/user-attachments/assets/4aa3fd4a-91d8-4a1f-bce9-0007a748db96)

NX console has problems loading the projects in the current workspace. Every once in a while reloading the window does resolve the problem.
![Image](https://github.com/user-attachments/assets/bdf3956e-50a3-4e18-97b4-edd002bc181a)

But then a day later or two it starts getting stuck in "We couldn't find any projects in this workspace." notice.

## Expected Behavior

The projects should be loading and visible in the NX Console extension tab.

## Steps to Reproduce

Install latest version on nx and nx-console extension and navigate to the extension tab.

### Failure Logs / Images / Videos

Unfortunately, no logs are shown that could further help me debugging.

- Nx Console version: 20.0.7
- VSCode version: Version: 1.95.1 (Universal)

**Comment by MaxKless** [comment]
Hi, 
could you provide some logs and ideally a minimal repro? That will make it easier for us to fix the issue. 
- Go to `Output -> Nx Language Server` and paste what you see there. 
- Run `Toggle Developer Tools` and paste what you see there too


Thank you!

**Comment by soosap** [comment]
Hi Max,

This is what I have in the `Output -> Nx Language Server`:

```
[Nxls] - 2024-11-04T16:56:04.314Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T16:56:04.314Z - Resetting daemon client

[Nxls] - 2024-11-04T16:56:04.314Z - Retrieved workspace configuration in: 3.972707998007536 ms

[Nxls] - 2024-11-04T16:56:04.320Z - Unregistering file watcher

[Nxls] - 2024-11-04T16:56:04.320Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T16:56:04.320Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T16:56:04.320Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T16:56:04.358Z - Initialized daemon watcher

[Nxls] - 2024-11-04T16:56:04.358Z - reconfiguration failed, trying again in 1 seconds

[Nxls] - 2024-11-04T18:14:41.756Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:41.757Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:41.757Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:41.757Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:41.757Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:41.757Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:41.759Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:41.760Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:41.760Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:41.760Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:41.760Z - Retrieved workspace configuration in: 4.44633299857378 ms

[Nxls] - 2024-11-04T18:14:41.767Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:41.767Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:41.769Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:41.769Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:41.803Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:41.803Z - reconfiguration failed, trying again in 4 seconds

[Nxls] - 2024-11-04T18:14:45.662Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:45.663Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:45.663Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:45.663Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:45.663Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:45.663Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:45.664Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:45.664Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:45.664Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:45.665Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:45.665Z - Retrieved workspace configuration in: 2.4592500030994415 ms

[Nxls] - 2024-11-04T18:14:45.668Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:45.668Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:45.669Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:45.669Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:45.703Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:45.703Z - reconfiguration failed, trying again in 9 seconds

[Nxls] - 2024-11-04T18:14:51.425Z - Files changed: .changeset/tiny-eyes-impress.md (delete)

[Nxls] - 2024-11-04T18:14:51.680Z - Files changed: apps/aathal/package.json (create), apps/aathal/CHANGELOG.md (create), config/corporate-identity/CHANGELOG.md (create), config/corporate-identity/package.json (create), libs/organisms/package.json (create), libs/organisms/CHANGELOG.md (create), apps/labs/CHANGELOG.md (create), apps/labs/package.json (create), libs/molecules/CHANGELOG.md (create), libs/molecules/package.json (create), libs/types/CHANGELOG.md (create), libs/types/package.json (create), libs/tables/package.json (create), libs/tables/CHANGELOG.md (create)

[Nxls] - 2024-11-04T18:14:52.681Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:52.682Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:52.682Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:52.682Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:52.682Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:52.682Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:52.682Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:52.683Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:52.683Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:52.683Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:52.683Z - Retrieved workspace configuration in: 1.511083997786045 ms

[Nxls] - 2024-11-04T18:14:52.685Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:52.686Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:52.686Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:52.686Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:52.711Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:52.711Z - reconfiguration failed after 3 attempts

[Nxls] - 2024-11-04T18:14:54.708Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:54.709Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:54.709Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:54.709Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:54.709Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:54.709Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:54.711Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:54.712Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:54.712Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:54.712Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:54.712Z - Retrieved workspace configuration in: 4.068291001021862 ms

[Nxls] - 2024-11-04T18:14:54.717Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:54.717Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:54.718Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:54.718Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:54.753Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:54.753Z - reconfiguration failed, trying again in 1 seconds

[Nxls] - 2024-11-04T18:14:55.754Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:55.754Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:55.754Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:55.754Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:55.754Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:55.754Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:55.755Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:55.755Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:55.755Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:55.755Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:55.755Z - Retrieved workspace configuration in: 1.2921249940991402 ms

[Nxls] - 2024-11-04T18:14:55.758Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:55.758Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:55.758Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:55.758Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:55.779Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:55.779Z - reconfiguration failed, trying again in 4 seconds

[Nxls] - 2024-11-04T18:14:59.781Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:14:59.781Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:14:59.781Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:59.781Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:14:59.781Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:14:59.781Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:14:59.782Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:14:59.782Z - Unable to get project graph

[Nxls] - 2024-11-04T18:14:59.782Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:14:59.782Z - Resetting daemon client

[Nxls] - 2024-11-04T18:14:59.782Z - Retrieved workspace configuration in: 1.5929999947547913 ms

[Nxls] - 2024-11-04T18:14:59.785Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:14:59.785Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:14:59.786Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:14:59.786Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:14:59.811Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:14:59.811Z - reconfiguration failed, trying again in 9 seconds

[Nxls] - 2024-11-04T18:15:08.812Z - Retrieving workspace configuration

[Nxls] - 2024-11-04T18:15:08.814Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2024-11-04T18:15:08.814Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/output.js

[Nxls] - 2024-11-04T18:15:08.814Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2024-11-04T18:15:08.814Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:15:08.815Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2024-11-04T18:15:08.818Z - createProjectGraphAndSourceMapsAsync

memory allocation of 29 bytes failed
[Nxls] - 2024-11-04T18:15:08.819Z - Unable to get project graph

[Nxls] - 2024-11-04T18:15:08.819Z - RuntimeError: unreachable
    at wasm://wasm/00b3fac2:wasm-function[3370]:0x24de56
    at wasm://wasm/00b3fac2:wasm-function[3303]:0x24dc6e
    at wasm://wasm/00b3fac2:wasm-function[3287]:0x24dbe9
    at wasm://wasm/00b3fac2:wasm-function[3174]:0x24d696
    at wasm://wasm/00b3fac2:wasm-function[3187]:0x24d73f
    at wasm://wasm/00b3fac2:wasm-function[3186]:0x24d734
    at wasm://wasm/00b3fac2:wasm-function[3182]:0x24d703
    at wasm://wasm/00b3fac2:wasm-function[2969]:0x24c31b
    at wasm://wasm/00b3fac2:wasm-function[174]:0xde627
    at wasm://wasm/00b3fac2:wasm-function[519]:0x181f67

[Nxls] - 2024-11-04T18:15:08.819Z - Resetting daemon client

[Nxls] - 2024-11-04T18:15:08.819Z - Retrieved workspace configuration in: 6.6162919998168945 ms

[Nxls] - 2024-11-04T18:15:08.826Z - Unregistering file watcher

[Nxls] - 2024-11-04T18:15:08.826Z - Daemon watcher connection closed

[Nxls] - 2024-11-04T18:15:08.827Z - Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/daemon/client/client.js

[Nxls] - 2024-11-04T18:15:08.827Z - Initializing daemon watcher 

[Nxls] - 2024-11-04T18:15:08.862Z - Initialized daemon watcher

[Nxls] - 2024-11-04T18:15:08.862Z - reconfiguration failed after 3 attempts
```

And this is the output from `Toggle Developer Tools`:

```
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope inline.graphql.
Old grammar file: file:///Users/soosap/.vscode/extensions/apollographql.vscode-apollo-2.3.6/syntaxes/graphql.js.json.
New grammar file: file:///Users/soosap/.vscode/extensions/graphql.vscode-graphql-syntax-1.3.8/grammars/graphql.js.json
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope inline.graphql.python.
Old grammar file: file:///Users/soosap/.vscode/extensions/apollographql.vscode-apollo-2.3.6/syntaxes/graphql.py.json.
New grammar file: file:///Users/soosap/.vscode/extensions/graphql.vscode-graphql-syntax-1.3.8/grammars/graphql.python.json
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.hcl.
Old grammar file: file:///Users/soosap/.vscode/extensions/hashicorp.hcl-0.6.0/syntaxes/hcl.tmGrammar.json.
New grammar file: file:///Users/soosap/.vscode/extensions/hashicorp.terraform-2.33.0-darwin-arm64/syntaxes/hcl.tmGrammar.json
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/soosap/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/soosap/.vscode/extensions/redhat.vscode-yaml-1.15.0/syntaxes/yaml.tmLanguage.json
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.nginx.
Old grammar file: file:///Users/soosap/.vscode/extensions/hangxingliu.vscode-nginx-conf-hint-0.3.1/src/syntax/nginx.tmLanguage.
New grammar file: file:///Users/soosap/.vscode/extensions/shanoor.vscode-nginx-0.6.0/syntaxes/nginx.tmLanguage
console.ts:137 [Extension Host] Activating prisma-language-server
console.ts:137 [Extension Host] Watching /Users/soosap/Projects/kadal for changes (old watcher).
console.ts:137 [Extension Host] Using published Language Server (npm)
console.ts:137 [Extension Host] serverModule: /Users/soosap/.vscode/extensions/prisma.prisma-5.21.1/node_modules/@prisma/language-server/dist/bin.js
4
console.ts:137 [Extension Host] Telemetry is enabled for Prisma extension
console.ts:137 [Extension Host] projectPath: /
console.ts:137 [Extension Host] Atom One Dark
2
console.ts:137 [Extension Host] Telemetry is enabled for Prisma extension
log.ts:419  INFO [perf] Render performance baseline is 16ms
abstractTaskService.ts:2087 Timed out getting tasks from  nx
console.ts:137 [Extension Host] [vscode-icons] v12.9.0 activated!
console.ts:137 [Extension Host] Telemetry is enabled for Prisma extension
console.ts:137 [Extension Host] Using local Nx package at /Users/soosap/Projects/kadal/node_modules/nx/src/utils/package-manager
lifecycle.ts:425 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at kai.add (lifecycle.ts:425:18)
    at pse.B (lifecycle.ts:497:22)
    at pse.addAction (contentHoverStatusBar.ts:44:23)
    at markerHoverParticipant.ts:239:23
log.ts:439   ERR [Extension Host] (node:27332) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Worker]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `Code Helper (Plugin) --trace-warnings ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:27332) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Worker]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `Code Helper (Plugin) --trace-warnings ...` to show where the warning was created)
log.ts:439   ERR Error: file:///Users/soosap/Projects/kadal/libs/tables/src/components/DataTable/stories/components/ClassicalComposers/columns.ts has changed in the meantime
    at YGe.q (bulkTextEdits.ts:218:13)
    at YGe.apply (bulkTextEdits.ts:291:8)
    at QGe.o (bulkEditService.ts:143:22)
    at QGe.perform (bulkEditService.ts:122:31)
    at ZGe.apply (bulkEditService.ts:245:37)
    at cRt.$tryApplyWorkspaceEdit (mainThreadBulkEdits.ts:33:32)
    at Pht.S (rpcProtocol.ts:458:17)
    at Pht.Q (rpcProtocol.ts:443:32)
    at Pht.M (rpcProtocol.ts:373:19)
    at Pht.L (rpcProtocol.ts:308:10)
log.ts:429  WARN IGNORING workspace edit: Error: file:///Users/soosap/Projects/kadal/libs/tables/src/components/DataTable/stories/components/ClassicalComposers/columns.ts has changed in the meantime
lifecycle.ts:425 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at kai.add (lifecycle.ts:425:18)
    at pse.B (lifecycle.ts:497:22)
    at pse.addAction (contentHoverStatusBar.ts:44:23)
    at markerHoverParticipant.ts:239:23
```

Wow I did not know I can debug like this. What do these errors mean? How can I increase the max listeners and what value should I set it to?

Thanks for looking into this.

**Comment by viachmev** [comment]
Have the same issue.

@soosap Do you know if there is any other ways to import a project e.g. manually? For me this is blocker as can not move forward to basically run the project.

**Comment by MaxKless** [comment]
are you seeing the sane error while using the cli @viachmev ?

**Comment by viachmev** [comment]
No, using the plugin 

![Image](https://github.com/user-attachments/assets/23797573-2c49-431c-92ab-eeade89bd582)

Managed somehow to get rid of an issue by using nx version 18.x rather then latest one 20.3.

**Comment by viachmev** [comment]
The final solution for myself - switched node version form 20 to 22 and now everything works even on the latest nx version (20.3).

**Comment by cforsyth68** [comment]
Exact same issue.  Any solution?

**Comment by svickers** [comment]
Try
`npm i @nx/nx-win32-x64-msvc`

That worked for me on 21.0.3.

**Comment by samuelho-dev** [comment]
Exact same issue here. Bumping for a solution.

**Comment by luizgamabh** [comment]
| ⚠️ Possible solution ⚠️ |
| --- |

Same issue here. The getNxWorkspacePath() function sometimes returns URL-encoded paths where backslashes are escaped as %5C.
For instance:
Expected: `"C:\www\myproject\nx.json"`
Actual: `"C:%5Cwww%5Cmyproject%5Cnx.json"`

The solution could be something similar to:

```javascript
export function getNxWorkspacePath(): string {
  const path = WorkspaceConfigurationStore.instance.get('nxWorkspacePath', '');
  
  if (path.includes('%')) {
    try {
      const decodedPath = decodeURIComponent(path);
      
      if (decodedPath !== path) {
        return decodedPath;
      }
    } catch (error) {
      // do nothing, return the original path
    }
  }
  
  return path;
}
```

I haven’t investigated it thoroughly due to lack of time — the adjustment may need to be made in other areas as well, but this is just to give a direction for solving the issue.

**Comment by MaxKless** [comment]
hmmm so strange, I'm not sure why this only sometimes happens? windows...
