### ISSUE TITLE
Generate UI not working

### ISSUE THREAD

**Issue by guisperandio** [nrwl/nx-console#959]
After the installation of ngx-spinner the generate ui option is not working anymore

npx nx report:
![image](https://user-images.githubusercontent.com/29610284/86274148-23b35f80-bbc9-11ea-8020-ea9c2d204f97.png)

VsCode version: 1.46.1
vscode log:
```
Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at readCollectionSchematics (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:166950:12)
    at readCollection (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:166939:16)
    at c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:166911:61
    at Array.map (<anonymous>)
    at readSchematicCollectionsFromNodeModules (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:166911:52)
    at readAllSchematicCollections (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:166857:29)
    at selectSchematic (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:132899:125)
    at getTaskExecutionSchema (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:168713:105)
    at revealWebViewPanel (c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:168541:138)
    at c:\Users\___\.vscode\extensions\nrwl.angular-console-12.0.0\main.js:169110:93
    at e._executeContributedCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:639:863)
    at e._doExecuteCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:639:38)
    at executeCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:914)
    at y._executeConvertedCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:708)
    at e._executeContributedCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:639:863)
    at e.$executeContributedCommand (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:217)
    at e._doInvokeHandler (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:1013)
    at e._invokeHandler (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:705)
    at e._receiveRequest (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:344)
    at e._receiveOneMessage (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:802:156)
    at c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:416
    at e.fire (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
    at v.fire (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
    at c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:649
    at e.fire (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
    at v.fire (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
    at t.PersistentProtocol._receiveMessage (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:243:629)
    at c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:824
    at e.fire (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
    at p.acceptChunk (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:737)
    at c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:89
    at Socket.t (c:\Users\___\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:185)
    at Socket.emit (events.js:203:13)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by isaacplmann** [comment]
This should be fixed in the next release. Fixed by #971
