### ISSUE TITLE
unknown webview handle in VS Code Nightly

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx-console#970]
Clicking on the Nx Console extension => Generate => Angular component results in a blank page with the following error in the developer tools:
``` bash
  ERR Unknown webview handle:7104c549-8513-418b-819c-718b6c63184f: Error: Unknown webview handle:7104c549-8513-418b-819c-718b6c63184f
    at I.getWebview (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6414:243)
    at I.$setHtml (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6411:159)
    at p._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4477:546)
    at p._invokeHandler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4477:238)
    at p._receiveRequest (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4475:901)
    at p._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4474:729)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4472:836
    at c.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:450:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:454:545)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:451:635
    at c.fire (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:447:445)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:446:796
    at Socket.t (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:456:185)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by isaacplmann** [comment]
Can't reproduce this in 1.49.0-insider
